### ISSUE TITLE
Crash when Genetic Waste is produced in the Advanced Mutatron

### ISSUE THREAD

**Issue by smudgerox** [bdew-minecraft/gendustry#10]
How to replicate: Mutate Ignoble Bees in the Adv. Mutatron.

Here's the crash: http://pastebin.com/peNwvuF9

Replicated on singleplayer, first happened with MCPC+ (for us).

**Comment by bdew** [comment]
Crap. I'll fix this ASAP.

**Comment by smudgerox** [comment]
Thank you!
