### ISSUE TITLE
Error When Automating with ME

### ISSUE THREAD

**Issue by Ryahn** [bdew-minecraft/gendustry#101]
When I tried to make anything with Genetics Processor. It becomes crafted as 6349:32767 when its 6349

I get this error when I used the 6349:32767
 Error: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.IllegalStateException: Crafting Tree construction failed.

I can manually craft them fine without using ME to automate it.

I made gif of it happening but it loads painfully slow, http://www.resonant-rise.com/uploads/imgs/2015-06-18_23-13-56.gif

**Comment by bdew** [comment]
DId you encode the pattern with AE2 Stuff Pattern Encoder by chance? If you did - this should be fixed in AE2Stuff 0.4.0

**Comment by Ryahn** [comment]
Will report back. Thanks <3
