### ISSUE TITLE
[Mod Interaction][Help]

### ISSUE THREAD

**Issue by ReikaKalseki** [bdew-minecraft/gendustry#102]
Is there a way to add new mutagen-producing items via an API or IMC? I do not understand scala, so reading the source did not help me find anything.

I would very much like to add my ReC nuclear waste and fuels as mutagen producers.

**Comment by bdew** [comment]
not right now i'll add something in the next version

**Comment by ReikaKalseki** [comment]
Thank you. :)

**Comment by bdew** [comment]
The API is in latest alpha (avalilable from [jenkins](http://jenkins.bdew.net/job/gendustry-1.7.10/) or [CF](http://minecraft.curseforge.com/mc-mods/70492-gendustry/files)).

I'll wait for a few days for comments/requests/bugs/etc. then make a new release.

**Comment by bdew** [comment]
Gendustry 1.4.14 is now out. Also i've switched to using semantic versioning for the API which is now version 2.0.0.

**Comment by ReikaKalseki** [comment]
:)
