### ISSUE TITLE
Full blocks not working as flowers with Gendustry-fu

### ISSUE THREAD

**Issue by grydian** [bdew-minecraft/gendustry#104]
Forstrey_dev fixed this bug for version 611.  Vanilla forestry apiaries work fine however the industrial apiary still is not recognizing the cactus for modest bees to work.  This is with gendustry-fu-1.5.0.39-mc1.7.10 and with forestry_1.7.10-3.7.0.612-unstable.  Thanks!  Love your mods!

**Comment by bdew** [comment]
The check is done by the bee code in forestry, unrelated to what apiary it's in. If they fixed it it should work in gendustry as well.

Did you try waiting for a bit? Flower checks are cached for some time.

**Comment by grydian** [comment]
I just reloaded the world.  I could not get the bees to see the flowers in the industrial apiary.  I even figured maybe the apiary needed to be broken and replaced.  Didn't work.  Switched bees around to use a different industrial apiary.  It showed it was working for a second and then went back to no flowers.  I can make screen shots if you like of it working in a forestry apiary and not in one of yours.  My best guess is they didnt take out the old code?  I have no idea why your apiary is not working and theirs is...  Again this is only with modest bees and cactus.  Full block flowers are not being recognized.

**Comment by bdew** [comment]
Are you sure it's fixed in forestry? Cactus doesn't seem to be detected with 612 for me...

Edit: If i make a 2 block high cactus - it works in both gendustry/forestry.
Edit 2: works for a bit then stops. *shrug*

**Comment by grydian** [comment]
Yeah I didn't give it enough time my bad.  Its just not working in forestry.  I will report the bug there.  Thanks for your help.

**Comment by bdew** [comment]
See my coments on ForestryMC/ForestryMC#737

Once they fix it it will work with gendustry too.

**Comment by grydian** [comment]
Thanks that worked like a charm.  You rock!
