### ISSUE TITLE
Can't breed leporine bee in advanced mutron

### ISSUE THREAD

**Issue by grydian** [bdew-minecraft/gendustry#105]
I have done this in many versions of your mod.  I love that I could breed the leporine bee.  When I put a forest princes and a medows drone I get two choices but both are common.  It used to be common and leporine.  I tried switching to medows princess and forest drone but same problem.  I even tested to see if it was a visual bug and tried both "common" bee options and it produced common bees both times.  Let me know if you need anymore information.  Using gendustry-fu-1.5.0.39-mc1.7.10 and forestry_1.7.10-3.7.0.612-unstable.

**Comment by bdew** [comment]
Intended, forestry "holiday" (tipsy, tricky, leporine, etc.) bees are now limited to the dates when they are normally available. See #100.

If you want the old behavior, you can make a custom config to enable them. Make a file <minectaft>/config/Gendustry/<whatever>.cfg:

```
cfg Genetics {
    cfg MutatronOverrides {
        "forestry.speciesLeporine" = ENABLED
        "forestry.speciesMerry" = ENABLED
        "forestry.speciesTipsy" = ENABLED
        "forestry.speciesTricky" = ENABLED
    }
}

```

**Comment by grydian** [comment]
Awesome thanks I have a few custom settings already and I can add that no problem.  You rock man!
