### ISSUE TITLE
java.lang.AbstractMethodError after updating Gendustry

### ISSUE THREAD

**Issue by utoc** [bdew-minecraft/gendustry#108]
Hello,

I wanted to report an error on the server console today in case it may be linked to a new issue, I've gotten the error about a dozen times since updating.  We did not crash.  If I need to crosspost this to EnderIO or provide any other information, please let me know

Fastcraft 1.21
Gendustry 1.5.1.106
BDlib 1.9.0.94
Forestry 3.6.2.19
EnderIO 2.2.8.381
FML 1448

Error seen here: http://pastebin.com/0H833k0m

EDIT: After having run the server for about 20 minutes, the error repeatedly run and brought the server to a halt.  File located at http://bbqsauce.terron.com/gendustry.zip

This may be related to https://github.com/bdew/gendustry/issues/107 but the EnderIO messages are different.  Thanks for looking at this.

**Comment by bdew** [comment]
Nothing to do with enderio (except that it causes a chunk to load with an apiary in it).

I think it's some other mod that isn't updated to the new forestry, i'll add a workaround for that.

The error is harmless except for console spam and shouldn't bring a server to a halt.

**Comment by bdew** [comment]
Try this build - http://jenkins.bdew.net/job/gendustry-1.7.10/107/artifact/build/libs/gendustry-1.5.2.107-mc1.7.10.jar

**Comment by utoc** [comment]
Strangely enough, with this test version of Gendustry I could not connect.  For sanity, I put the previous version of Gendustry 1.5.1.106 back in on both server and client and I was able to connect again.  Kept getting "timed out"

Here is a profile sample using Player's sampler mod and the fml log if either of them can help: http://bbqsauce.terron.com/gendustry-2.zip

**Comment by bdew** [comment]
I have no idea why that would happen. I did some testing with a server and couldn't reproduce it. Moreover i don't even see any of my code running in your sampler snapshot (but i don't really have a lot of experience interpreting them).

Added: The fix should actually make things faster if anything, because i made the sanity checker run once when the first apiary is placed/loaded. It was using every time one was placed/loaded before.

**Comment by utoc** [comment]
I'll try removing a few Forestry mods today (Like Binnie's) and see if I'm able to connect after.  I'll get back with you.

**Comment by utoc** [comment]
I did some testing just now and was able to connect with 1.5.2.107. Strangely enough I didn't make any changes to the server or the client.  I'm going to call it a gremlin.  Anyway, with that version, I did not get console spam and the issue appears to be fixed with that update.  Thanks for knocking that issue out.
