### ISSUE TITLE
Enhancement Request: Support uranium-235 & uranium-238 from Applied Science mod

### ISSUE THREAD

**Issue by jalapeno777** [bdew-minecraft/gendustry#11]
Without IC2 on a server there aren't many options for mutagen that are decent.  I am requesting the ability to include uranium-235 and 238 from applied science as a mutagen producer.

On a side note, a custom config to be able to specify the items that can be used and their mutagen value would allow for a lot more options for a server owner =)

**Comment by bdew** [comment]
There is a config for that, though it's not really well documented yet...

There's an [example in the forum thread](http://www.minecraftforum.net/topic/2160265-gendustry-103-updated-24012014/page__st__60#entry27493597) about how to add AS uranium.

I thought about adding it to the default config, but i'm not sure what good default values would be... any suggestions?

**Comment by bdew** [comment]
So are 1000/2000mb good defaults? Unless someone claims otherwise i will add it to the default config for next version :P

**Comment by jalapeno777** [comment]
I think they're a good default to work with, especially considering the
extra effort required to refine the ore.

Have you put any consideration into adding bees directly into your mod as
well?  As far as I am aware Extra Bees at this point is dead in the water
which makes your mod a lifesaver especially for 1.7...but there will be a
giant gap of missing bees in 1.7 right now.

**Comment by bdew** [comment]
I'm undecided on adding bees as part of this mod. On one hand i understand the situation with EB and would like to provide some solution. On the other i have very limited time to work on modding lately and would like to spend more of it on other stuff (like DCM which development has been stalling for months now). It might be required for someone else to step up to fill that hole.

At any rate i haven't reached any conclusive decision for now.

**Comment by jalapeno777** [comment]
For what it's worth, I'd be happy to help.  Unfortunately most of my
modding experience falls under bukkit programming but if you ever decide to
move forward and can at least setup some form of basic framework...myself
or my server team could easily work at actually devising the bees to be
used and creating the texture graphics.

I could probably mod them in myself eventually but forge modding is very
new to me and I'd be just as likely to blow something up haha.

**Comment by bdew** [comment]
AS uranium is now in the default config so i'm closing this issue.

For adding custom bees i'm currently working out a system that will allow creating custom bees using a text format, with no coding required ([something like that](https://github.com/bdew/gendustry/blob/custom-bees/resources/assets/gendustry/gendustry-bees.cfg)) I'll make a forum post about it once the system is more finished.
