### ISSUE TITLE
Client crash with latest Gendusty (1.5.2 107)

### ISSUE THREAD

**Issue by Haggle1996** [bdew-minecraft/gendustry#110]
http://pastebin.com/KyfjBDrm

Crash on startup.

**Comment by Haggle1996** [comment]
I've narrowed this down to a problem with the newest version of DragonAPI from @ReikaKalseki. Having v7 of DragonAPI in the folder explodes Gendustry. Here's a more focused crashlog with only DragonAPI.

http://pastebin.com/E1dyPU6Z

**Comment by RoloEdits** [comment]
can also confirm this happened to me after updating dragonapi, reactor craft, electric craft, and rotary craft.

**Comment by bdew** [comment]
> Caused by: java.lang.SecurityException: class "net.bdew.gendustry.api.blocks.IForestryMultiErrorSource"'s signer information does not match signer information of other classes in the same package

I'm not sure why Reika needs to ship my API at all, but he most definitely should not be signing it.

I don't think there's anything i can do to fix it from my side.

**Comment by ReikaKalseki** [comment]
I do not ship the Gendustry API.

EDIT:
Make that "intentionally".

This will be fixed in v7b. Until then, delete the API from my jar.

**Comment by bdew** [comment]
http://i.imgur.com/ax6seqA.png

And it's signed in your jar

**Comment by ReikaKalseki** [comment]
This is fixed for v7b.
