### ISSUE TITLE
Steam Turbine Showing Empty Of Steam When its Not

### ISSUE THREAD

**Issue by RoloEdits** [bdew-minecraft/gendustry#113]
after thinking im not making any steam i put a bedrockium drum in between to see if that was the case and i was and making a lot of it to and when hooking that up to the fluid input valve the tank still shows empty

![2015-07-09_03 49 23](https://cloud.githubusercontent.com/assets/12489689/8593556/a250e686-25ed-11e5-91d9-8d1164be38c8.png)

![2015-07-09_03 49 30](https://cloud.githubusercontent.com/assets/12489689/8593558/a8c8d118-25ed-11e5-9a04-29cb61078aa3.png)

![2015-07-09_03 49 45](https://cloud.githubusercontent.com/assets/12489689/8593562/b095e6ce-25ed-11e5-937d-64de55918495.png)

![2015-07-09_03 49 48](https://cloud.githubusercontent.com/assets/12489689/8593564/b6d13818-25ed-11e5-9b0b-c70033e09ba2.png)

and is it always supposed to use 3200 mB/t?

**Comment by RoloEdits** [comment]
maybe never mind after breaking and replacing the tank controller and input valve seems to have fixed it

**Comment by bdew** [comment]
It's using 3.2k mb per tick, which is less than it's maximum total throughput (6250 mb/t i guess) so no steam is left in the tank. The buffer will fill up only if you pipe in more than it can use.

**Comment by RoloEdits** [comment]
thank you for your help
