### ISSUE TITLE
Make it compitable with FU #640

### ISSUE THREAD

**Issue by erkro1** [bdew-minecraft/gendustry#115]
Since forestry unstable version 640 it crashes, probably because of the 'Giant multiblock refactor'.
http://ic2api.player.to:8080/job/Forestry_Dev/640/

Also thank you for making this (and other) awesome mods!

**Comment by bdew** [comment]
Fixed all compile errors in 6cd613a85c9ce6e819ea2c2b94ee5ca395f14f2c

No testing whatsoever, if anyone wants to try it - http://jenkins.bdew.net/job/gendustry-1.7.10-fu/43/

**Comment by Xen1290** [comment]
@bdew tested, result : crash
Here the crash report:
Forestry 4.0.0.644
https://gist.github.com/Xen1290/a6407f565c9a9cb584fa

**Comment by bdew** [comment]
Fixed the crash and a bunch of other bugs in http://jenkins.bdew.net/job/gendustry-1.7.10-fu/44/ - try this one
