### ISSUE TITLE
Another Crash with Forestry 4.0.0.652-unstable

### ISSUE THREAD

**Issue by Xen1290** [bdew-minecraft/gendustry#118]
Hi @bdew ,
here the crash report: 
https://gist.github.com/Xen1290/0a33f4abc97daf322902
Gendustry version:
gendustry-fu-1.6.0.46-mc1.7.10  from jenkins

**Comment by bdew** [comment]
Looks like it just needs a recompile with the new API. New build will be here in a few sconds: http://jenkins.bdew.net/job/gendustry-1.7.10-fu/47/

**Comment by Xen1290** [comment]
Thanks @bdew ! I'll try later

**Comment by Xen1290** [comment]
Fixed, thanks
