### ISSUE TITLE
[Balance] Entry into Gendustry

### ISSUE THREAD

**Issue by smudgerox** [bdew-minecraft/gendustry#12]
As it is currently, anybody with little to no bee experience can breed very high tier bees within an hour, such as Withering or Diamond. What I would suggest is use something along the lines of Royal Jelly, at a small item-to-mutagen rate. What would be even better is create a new line/species of bee that produces something like Mutagen drops that you can turn into liquid. The Labware should also require something harder to get.

**Comment by bdew** [comment]
This mod was meant to remove tedium and time sinks from the bee/tree breeding process, adding them back in a different would be counter-productive to it's goal. Most of the things you suggested can be edited in the config if one desires for his server/world.

Besides, i don't think the bug tracker is a good place to discuss balance, the forum thread would be better where other users can weight in, this is not an actual "bug".
