### ISSUE TITLE
Crash with forestry-unstable rev 639+ for Gendustry

### ISSUE THREAD

**Issue by davv1** [bdew-minecraft/gendustry#120]
https://github.com/ForestryMC/ForestryMC/issues/785

I just pasted link of my opened issue in Forestry's GitHub, if it's wrong then I'll make a just new issue.

**Comment by bdew** [comment]
Forestry unstable 4.0 has incompatible API changes, so the normal builds of Gendustry won't work with it.

There's a sepearate branch of Gendustry for forestry unstable, see here http://jenkins.bdew.net/job/gendustry-1.7.10-fu/

**Comment by davv1** [comment]
Does this have same features as normal branch of Gendustry?

**Comment by bdew** [comment]
Yes, i try to keep them in sync most of the time. Once Forestry 4.0 comes out that code will become the next version of Gendustry and a new -fu branch will be started for 4.1 or whatever.

**Comment by davv1** [comment]
Thanks guys for your help.
