### ISSUE TITLE
Clear sky upgrade not working

### ISSUE THREAD

**Issue by Michal-MK** [bdew-minecraft/gendustry#121]
Forge: 1448
Forestry: 3.6.3.20
Gendusty:1.4.8.65

When I put the upgrade in, the "sky is obstructed" error disapeard but the percentage bar did not want to move (like the error was stil there).
then I tried it outside without the upgrade and that worked fine.

E: When it is night time the Industrial Apiary doen't show the Night Error- probably is the cause.

**Comment by bdew** [comment]
Gendustry 1.4.8 is not fully compatible with forestry 3.6.x - try with 1.5.2 and check if it still happens.

**Comment by Michal-MK** [comment]
Tried the latest build from Jenkins, fixes the problem (forgot to update gendustry with the rest of the mods a week back :) )
Closing this Issue ..?
