### ISSUE TITLE
[Suggestion] Redstone output for apiaries

### ISSUE THREAD

**Issue by xenoflot** [bdew-minecraft/gendustry#128]
Hi,

I've been playing with large scale (well, 16 apiaries) production for the first time tonight. It would be helpful if there was a way to raise an alarm when the apiary is in an error state. At the very least it would be nice to stick a lamp on top but ideally running redstone wire or conduits to do something more fancy (like extract the bee, write a fresh genome template over it and send it back).

Also (according to the internet) the Leporine bee seems only breedable during easter. That seems quite daft, perhaps the adv mutatron could override these seasonal restrictions?

Cheers

**Comment by bdew** [comment]
If you have buildcraft you can detect error states using gates. I'll consider some alternative form of signaling but i don't have a good elegant solution that i like at the moment.

Seasonal holiday bees are set to respect their mutation limits (set by forestry) by default, but you can force them to be available at all time by making a file **minectaft/config/Gendustry/<whatever>.cfg** with something like that:

```
cfg Genetics {
    cfg MutatronOverrides {
        "forestry.speciesLeporine" = ENABLED
        "forestry.speciesMerry" = ENABLED
        "forestry.speciesTipsy" = ENABLED
        "forestry.speciesTricky" = ENABLED
    }
}
```

**Comment by xenoflot** [comment]
OK I'll look into some BC pipes (yes, the pack has BC7). Thanks for the tip on the festive bees.

As to alternative signalling, I expect that it would be very difficult to process an encoded output for the several possible error states. A simple button that toggles on "emit redstone on error" would be a boon.

**Comment by bdew** [comment]
I have an idea to make a "sensor cover" which goes on one side of an apiary and can detect varous error conditions and emit redstone from that side.

This is a reminder to myself to look at the code to see how feasible that would be

**Comment by bdew** [comment]
Should be in next alpha build.

**Comment by xenoflot** [comment]
Fantastic! Thanks!
