### ISSUE TITLE
Latest BDLib kaput

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [bdew-minecraft/gendustry#13]
Yo! Is kaput, the latest BDLib. I tells ya! http://paste.ee/p/ZsNnu

**Comment by bdew** [comment]
A compatible version will be on jenkins shortly. Note that BdLib is in a bit of a flux right now with many changes happening for a different mod i'm working on and Gendustry isn't always up to date with those changes, i recommended using the stable versions on my download page unless you like stuff breaking :P
