### ISSUE TITLE
Industrial Apiary Instatly Bee conversion

### ISSUE THREAD

**Issue by ghost** [bdew-minecraft/gendustry#135]
gendustry-1.5.2.107-mc1.7.10

If you have a queen inside one Industrial Apiary doing its process and you swap it up to another queen WITHOUT removing the first queen, by the moment the percentage bar rises the bee will be instantly converted to the previous type of bee in the machine.

For example: I had a Vis Queen inside the Industrial Apiary and I was changing a Rocky Princess over to Vis princess using a normal Apiary from Forestry, so I decided to switch em up to speed up the process. When I moved the Rocky Queen to the Industrial Apiary without previously removing the Vis queen (switching up the currently item on the cursor) I realized it instantly converted over to the same stats as the previous queen on the machine.

**Comment by bdew** [comment]
Looks like a bug in Forestry 3.6.x, it also happens with the vanilla apiaries.

It's not happening with Forestry 4.0 which should come out soon(tm).

https://github.com/ForestryMC/ForestryMC/issues/817

**Comment by bdew** [comment]
Should be fixed in Forestry 3.6.5 stable
