### ISSUE TITLE
Crash at startup with newest Forestry 4

### ISSUE THREAD

**Issue by AlexPlus117** [bdew-minecraft/gendustry#139]
My client crashes each time I try to load it with GenDestry and newest Forestry 4. Here's the report: http://pastebin.com/WGY5KyWA

**Comment by bdew** [comment]
You need to use the -fu versions of gendustry with forestry 4.0 beta.

http://minecraft.curseforge.com/mc-mods/70492-gendustry/files/2259909

**Comment by Dream-Master** [comment]
@bdew 
I get the same/similar crash with the stable Version 4.0.2.30 from Forestry.
Have to using the fu branche here too ?
http://jenkins.ic2.player.to/job/Forestry/30/

**Comment by bdew** [comment]
4.0.2 is beta, the last stable forestry is 3.6.x
yes you need to use fu from for anything 4.0 until it's officially released and i merge the fu branch into the main one.

**Comment by Dream-Master** [comment]
Ok crash too because binnies Mod ;-(

**Comment by bdew** [comment]
Yeah there's a bunch of backwards incompatible stuff in 4.0, all addons need to be updated

**Comment by Dream-Master** [comment]
Using old version than and hope Binnie and the others will fix it soon.
Thanks for help.

**Comment by AlexPlus117** [comment]
I reported this to Binnie, but he's inactive and he isn't replying any of its mods bugs.

**Comment by Dream-Master** [comment]
Yes we can only hope that he have time on christmas when he have probably free time.

**Comment by AlexPlus117** [comment]
WHAT? CHRISTMAS? I don't have patience to wait until then.

**Comment by AlexPlus117** [comment]
Anyway, there's another crash with GenDustry: http://pastebin.com/3MDjtiTF

**Comment by bdew** [comment]
Probably another mod that adds bees that isn't updated to Forestry 4.0 API. Maybe Magic Bees?
