### ISSUE TITLE
No Gene Sample for Saplings Alleles 

### ISSUE THREAD

**Issue by dudgybudgie** [bdew-minecraft/gendustry#14]
I was trying to produce an apple oak sapling with high sappiness, yield and saplings. I was able to produce a sample for yield and sappiness but couldn't produce one for saplings. I went into a test world and set up three Genetic Samplers with 64 saplings but none of them produces a saplings sample.
Looking in NEI there isn't one there either.

**Comment by bdew** [comment]
It's there but called "Fertility" instead of "Saplings" in gendustry because the name is shared between bees/trees/butterflies. There shouldn't be any issues with getting them as far as i can see.
