### ISSUE TITLE
Forestry 4 start up crash 

### ISSUE THREAD

**Issue by RoloEdits** [bdew-minecraft/gendustry#140]
http://pastebin.com/kjLwtNuq

gendustry-fu-1.6.1.53-mc1.7.10

forestry_1.7.10-4.0.3.31

**Comment by bdew** [comment]
Some other forestry addon is not updated to the API changes in Forestry 4 - probably Magic Bees

**Comment by RoloEdits** [comment]
OK, Thank you for you time :)
