### ISSUE TITLE
Strange behavior of bees in Industrial Apiary.

### ISSUE THREAD

**Issue by OneEyeMaker** [bdew-minecraft/gendustry#141]
Hello.
Perhaps, it is standard mechanics... but the first time I faced a similar behavior of bees...
ANY Pristine bees in Industrial Apiary transform into Ignoble in few minutes!

I can reproduce this with any bee from Forestry/Gendustry/Magic Bees.

I can't guess, where problem (?) is... Maybe I made a mistake in Gendustry configuration file...

P. S.
Forestry 3.6.10, Gendustry 1.6.1, BDLib 1.9.3
I can provide any other information if needed.

P. P. S. Sorry for my English, I'm from Russia.

**Comment by OneEyeMaker** [comment]
And I noticed, that it happens only when there is a bunch of production upgrades in apiary.

**Comment by OneEyeMaker** [comment]
Sorry, I found problem in my config file.

https://github.com/bdew/gendustry/blob/647fe4d9af4407388420b6d48a075429c8fb50c6/src/net/bdew/gendustry/api/ApiaryModifiers.java#L36

**Comment by bdew** [comment]
FYI the limit is 16 nowadays, i need to update that comment.

It's sadly [hardcoded in forestry](https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/apiculture/genetics/BeekeepingMode.java#L98) and can't be changed.

**Comment by OneEyeMaker** [comment]
Thank you for information.
