### ISSUE TITLE
[Enhancement] Precision mode for industrial grafter

### ISSUE THREAD

**Issue by mikeloeven** [bdew-minecraft/gendustry#142]
So i saw the industrial grafter and was like OH COOL a grafter that runs on RF than when i tested it out i found to my horror that a single tap of the mouse took out almost all the leaf blocks on my trees this is really annoying when your trying to do controlled cross breeding of trees i would like to see a precision mode that allows you to harvest one leaf block at a time when you right click

**Comment by bdew** [comment]
Will add

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
