### ISSUE TITLE
GUI text and Icons missing texture's after update.

### ISSUE THREAD

**Issue by ghost** [bdew-minecraft/gendustry#143]
After upgrading to 1.6.2.127 the login screen is unreadable. Tested with with modpack and fresh setup.
http://imgur.com/ekB3k2p
http://imgur.com/xLyPCVT
http://imgur.com/YE5pUEx

Setup:
Java: 8 Update 65
Forge : 10.13.4.1492 & 10.13.4.1517
Mod List:
bdlib-1.9.3.107-mc1.7.10.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
forestry_1.7.10-4.0.11.40.jar
gendustry-1.6.2.127-mc1.7.10.jar
magicbees-1.7.10-2.4.0.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar

**Comment by bdew** [comment]
Is that on a mac by chance? Looks like this bug https://github.com/MinecraftForge/MinecraftForge/issues/1829

Try disabling forge splash screen as suggested there.

I highly doubt that any of my mods are doing anything that can break all the textures like that.

**Comment by ghost** [comment]
bdew,
   This seemed to have fixed it, but the odd part is before I sent you the bug I tested and it only happened when I updated to gendustry-1.6.2.127-mc1.7.10.jar. If I disabled or removed the mod it didn't happen.

For any other Mac user here is what I changed. The link able is way to long, and filled with unhelpful comments.

In your config folder there is a hidden file called splash.properties.
Change:

```
enabled=true
```

To

```
enabled=false
```

**Comment by bdew** [comment]
Yeah it's triggered by some mods being present or not, or possibly by the number of mods or textures being loaded. 

At any rate the problem is somewhere between Forge and Mac drivers, and forge maintainers don't seem to be too interested in really fixing it, nothing i can do about it on my side.
