### ISSUE TITLE
Lots of BeeFX

### ISSUE THREAD

**Issue by mezz** [bdew-minecraft/gendustry#144]
Industrial Apiaries do `beeLogic.doBeeFX()` on every tick.
Forestry Bee Houses and Apiaries do it every 4 ticks, and Alvearies are every 2 ticks.

**Comment by bdew** [comment]
I kinda like the current frequency, but i can see that it can be irritating and bad for performance in large arrays of apiaries :P

I'm adding a (client side) option to set the frequency, default to once every 2 ticks.
