### ISSUE TITLE
[Issue] Genetic Imprinter outputting Unknown Genome On Full Template?

### ISSUE THREAD

**Issue by mikeloeven** [bdew-minecraft/gendustry#145]
Not sure if this is an issue of just an oversight however i am not certain why the genetic imprinter outputs saplings and bees with unknown genome when using a complete template. I dont see why the imprinters output would need to be re analyzed since even if your supplying unknown sampls as the source the output will all be of a uniform and known genetic code. with incomplete and partial templates i can understand this behavior but when using a complete 13 chromosome sample the output should be known

**Comment by bdew** [comment]
Good point, i'll change this.
