### ISSUE TITLE
Compatibility problem.

### ISSUE THREAD

**Issue by OneEyeMaker** [bdew-minecraft/gendustry#148]
Newest Gendustry (1.6.3) doesn't work correctly with latest Forestry (4.2.1): mod can't register any bees (= "colored" bees aren't available in game). In the same time Forestry many times reports about fatal error in log: `Missing allele: {null, null}`.

But with Gendustry 1.6.2 all works fine.

**Comment by Tsyklop** [comment]
same problem.

**Comment by OneEyeMaker** [comment]
// @Tsyklop Приветствую, мой "одноглазый коллега".
@bdew 
It seems problem is caused by GenDustry, not Forestry: I tested 4 times with these versions:
- Forestry 4.2.0 + GenDustry 1.6.2 = works fine
- Forestry 4.2.1 + GenDustry 1.6.2 = works fine
- Forestry 4.2.0 + GenDustry 1.6.3 = Forestry can't register "colored" bees.
- Forestry 4.2.1 + GenDustry 1.6.3 = Forestry can't register "colored" bees.

**Comment by bdew** [comment]
Custom bee registration should be fixed in this build: http://minecraft.curseforge.com/projects/gendustry/files/2269234

Don't think the log spam is related to this, tho i will look into it.
