### ISSUE TITLE
[Bug or Feature] Strange amount of bee products.

### ISSUE THREAD

**Issue by OneEyeMaker** [bdew-minecraft/gendustry#149]
Hello, @bdew 
I noticed strange behavior of bees in Industrial Apiary with production upgrade(s). 
Many bees have two (or more) product types with different chances to get ones. For example, Endearing bee (MagicBees) should produce Enderium nugget (with 90% chance), Endearing Comb (50%) and Mysterious Comb (10%). And in Industrial Apiary (without Production upgrades) it does. But with production upgrades amount of products of each type is equal. Is it bug or feature?
If I understand correctly, this amount calculates as:
`chance_to_get_product * (bee.speed * apiary.production_modifier) * (bee.lifespan * apiary.lifespan_modifier)`.
But why I'm getting equal amount of each type of bee product? Is there some limitations in calculation (in code)? Or is this bug?

P. S. Sorry for my English, I'm from Russia.

**Comment by bdew** [comment]
This is a limitation in Forestry. Once your modified chance goes above 100% you will get one product for each "bee tick" and that's it. Anything above that will not increase production further.

The relevant code is here if you're interested: https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/apiculture/genetics/Bee.java#L504-L528
