### ISSUE TITLE
Custom bees centrifuge recipe no recognising techreborn items

### ISSUE THREAD

**Issue by popbangshwang** [bdew-minecraft/gendustry#150]
This is an interesting one, and I'm not entirely sure where the problem lies (gendustry or elsewhere).
I have the following centrifuge recipe:
    centrifuge: S:gendustry:"HoneyComb.Bronze", 40 cycles => {
        100% OD:dustSmallBronze
        50% I:Forestry:beeswax
        25% I:Forestry:honeyDrop
    }
The only item that doesnt show ingame is the 100% OD:dustSmallBronze
I have tried both the ore dictionary and techreborn:smallDust@12 - neither of which work.
Adding the recipe with minetweaker works without any issue
Using COFH core worldgen, referencing techreborn blocks works fine as well.

**Comment by bdew** [comment]
Problem is that techreborn registers it's items in Init - unlike most mods that do it in PreInit, and gendustry resolves the recipes before the item is registered.

I'm going to try move that resolving to a later stage, which should fix this (and probably similar issues with other mods), but i'm not sure if it would break something else.

**Comment by bdew** [comment]
Please test this build: http://jenkins.bdew.net/job/gendustry-1.7.10/133/artifact/build/libs/gendustry-1.6.4.133-mc1.7.10.jar

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
