### ISSUE TITLE
Feature request: dimension / generator specific spawns

### ISSUE THREAD

**Issue by keybounce** [bdew-minecraft/gendustry#152]
I'd like to be able to make some spawns dependent on dimension, or on world generator / chunk provider, if possible.

The goal: Have some bees that only spawn in mystcraft ages, other that only spawn in RfTools dimensions, others that only spawn in specific dimensions.

This is for a server that is going to be based around exploration in multiple worlds (with different gating)

**Comment by bdew** [comment]
It seems that they use the same chunk provider as vanilla however i could detect the world provider which is different.

I'll add this soon(tm)

For the record the world provider classes are:
- MystCraft - com.xcompwiz.mystcraft.world.WorldProviderMyst
- RFTools - mcjty.rftools.dimension.world.GenericWorldProvider
- Vanilla - net.minecraft.world.WorldProviderSurface / net.minecraft.world.WorldProviderEnd / net.minecraft.world.WorldProviderHell

**Comment by keybounce** [comment]
Thank you.

And, I thought ChunkProviderMyst was the chunk provider for mystcraft. Did that change? I last checked in 164.

**Comment by bdew** [comment]
I haven't looked at it too deeply, just poked around with a debugger running with both mods - all dimensions (both vanilla and modded) were using net.minecraft.world.gen.ChunkProviderServer

**Comment by keybounce** [comment]
ChunkProviderServer is the "read data from disk" class.

ChunkProviderGenerate is the vanilla "create the chunk" class

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
