### ISSUE TITLE
Try to add custom Bee Products via Gendustry config not working

### ISSUE THREAD

**Issue by Dream-Master** [bdew-minecraft/gendustry#156]
I try to add custom items from the Core Mod of my Modpack as bee products to the Centrifuge.
The log says Item stack not found. All other Mods items works fine.

I try this

```
centrifuge: S:gendustry:"HoneyComb.naga", 40 cycles => {
    33% S:dreamcraft:"item.NagaScaleChip"
    5% S:dreamcraft:"item.NagaScaleFragment"
    30% I:Forestry:beeswax
    5% I:MagicBees:propolis@4 // Earth Propolis
```

and this

```
centrifuge: S:gendustry:"HoneyComb.naga", 40 cycles => {
    33% I:dreamcraft:"item.NagaScaleChip"
    5% I:dreamcraft:"item.NagaScaleFragment"
    30% I:Forestry:beeswax
    5% I:MagicBees:propolis@4 // Earth Propolis`
```

not works.

Log:

```
[22:46:54] [Client thread/DEBUG] [gendustry/gendustry]: Adding centrifuge recipe: StackGeneric(gendustry,HoneyComb.naga) => List((33.0,StackItem(minecraft,item.NagaScaleChip,32767)), (5.0,StackItem(minecraft,item.NagaScaleFragment,32767)), (30.0,StackItem(Forestry,beeswax,32767)), (5.0,StackItem(MagicBees,propolis,4)))
[22:46:54] [Client thread/WARN] [bdlib/gendustry]: Unable to resolve StackItem(minecraft,item.NagaScaleChip,32767): Item not found minecraft:item.NagaScaleChip
[22:46:54] [Client thread/WARN] [bdlib/gendustry]: Unable to resolve StackItem(minecraft,item.NagaScaleFragment,32767): Item not found minecraft:item.NagaScaleFragment
[22:46:54] [Client thread/DEBUG] [bdlib/gendustry]: meta/damage is unset in StackItem(Forestry,beeswax,32767), defaulting to 0
[22:46:54] [Client thread/DEBUG] [gendustry/gendustry]: Done 1xitem.gendustry.HoneyComb@1000 -> {1xitem.for.beeswax@0=0.3, 1xitem.propolis@4=0.05}
```

In the registry.dump file i see the items like i wrote it (no spelling errors)

```
dreamcraft:item.NagaScaleChip
dreamcraft:item.NagaScaleFragment
```

![image](https://cloud.githubusercontent.com/assets/2970688/13477031/cf5af20a-e0ca-11e5-9b4e-5cdab1a739a2.png)

![image](https://cloud.githubusercontent.com/assets/2970688/13477045/da477e22-e0ca-11e5-8f40-007ebfa550d2.png)

This is the Core Mod (Namikon the Author is away atm that's why i asking here)

https://github.com/GTNewHorizons/NewHorizonsCoreMod

Item list registered here:

https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/item/ItemList.java

Changes/additions i made:

https://github.com/GTNewHorizons/NewHorizons/commit/a0cf34dce4cbdfb9d2df5d77de8035daa0151fe0

The Core Mod need YAMCL

https://github.com/GTNewHorizons/Yamcl

Can this be the problem (how he mod registered items)?
https://github.com/GTNewHorizons/Yamcl/blob/de084e60c86b1d8a807eddb876c873f854da5c34/src/main/java/eu/usrv/yamcore/items/ModItemManager.java#L81

I hope i get help here.

Thanks in advance

**Comment by Teteros** [comment]
From Bdew's (BACON) [ItemStack](https://bdew.net/bacon/itemstack-references/) reference:
`S:{modid}:{name} – Custom ItemStack (registered with forge registerCustomItemStack)`
expects `registerCustomItemStack` so that might be it.

Should mention the `ModSimpleBaseItem` constructor which is found [here](https://github.com/GTNewHorizons/Yamcl/blob/de084e60c86b1d8a807eddb876c873f854da5c34/src/main/java/eu/usrv/yamcore/items/ModSimpleBaseItem.java#L22).

**Comment by bdew** [comment]
It's using GameRegistry.registerItem - so you need to use the I:... version.

I don't see why that wouldn't work. Can you please try again with that form and if it fails upload the full client log somewhere?

**Comment by Dream-Master** [comment]
Sure will do tomorrow.

**Comment by Dream-Master** [comment]
Not working with "I-Version" too.

Ok here the FML Log:
https://gist.github.com/Dream-Master/340d335d330386dfa825#file-fml-log

Here my Pack (Technic Launcher instance)
https://www.dropbox.com/s/25ku32d5mv27phd/mcnewhorizons.zip?dl=0

**Comment by bdew** [comment]
Please try this version - http://jenkins.bdew.net/job/gendustry-1.7.10/133/artifact/build/libs/gendustry-1.6.4.133-mc1.7.10.jar

That build is identical to the last release version, except that I've moved recipe loading from init to postInit and i think this will fix your issue as well (You are registering the items in init, and it's getting called after gendustry, so the items don't exist yet when it looks for them).

**Comment by Dream-Master** [comment]
Thanks for the fast replay.
We using Forestry 3.6 because of Binnies mod. We will update in the future because there is a binnie patcher now. Is version 133 Forestry 3 compatible?

**Comment by Dream-Master** [comment]
Is this the line change the things ?
https://github.com/bdew/gendustry/commit/746bcf63d08809a8b642b9ff8b29f3dcb1a578ea
If yes i can try to fork your project and build my own version with the olkd version if possible.

**Comment by bdew** [comment]
Yeah that's the change.

You could also change your mod to have before:gendustry in it's dependencies so that it will load before. Or maybe move that item registration to preInit if that's feasible.

**Comment by Dream-Master** [comment]
I thinking about different solutions.
before:gendustry i will try first.
I also try too add those recipe via Java to the Core mod (Gregtech Centrifuge recipe) make it more flexible in EU usage and Time need for centrifuge.
Thanks for the help. When it works i will close the issue.

**Comment by Dream-Master** [comment]
I adding it via Minetweaker.
