### ISSUE TITLE
Can't put Bees in the DNA Extractor slot

### ISSUE THREAD

**Issue by Dream-Master** [bdew-minecraft/gendustry#157]
Since i updatet my pack to Forestry 4 thanks Binnies Patcher for Binnies mod i change to the lastest Gendustry version. Now we find out that we can't put Bees in the DN Extractor slot any more. I added some saplings and other ingredients in the cfg file this are the only items that worked.

Find out with the Protein we have the same issue here.

My Modpack
https://github.com/GTNewHorizons/NewHorizons

Using Mods Forestry 4.2.11.59, Gendustry 1.6.4.134, Binnies Mods pre 14 and binnies Patcher 1.6

https://github.com/GTNewHorizons/NewHorizons/issues/561

**Comment by bdew** [comment]
Odd. I can't reproduce it with just the listed mods and versions, might be something else involved...
- Where are the bees you are trying to put in coming from? (Spawned from NEI?)
- Are you doing anything funny with the configs?
- Anything fishy in the logs (DNA sources should produce a message on debug level when registering - "Added Liquid DNA source...")
- Click the arrow in extractor GUI to see recipes in NEI, does it list bees?
- Does it still happen if you temporarily take out binnies mods and the patcher?

**Comment by Dream-Master** [comment]
if i add all saplings and bees via cfg back and it will work.

I not try to remove binnies mods and the recipes are not shown in nei and yes i spawn them via nei. I remember it works before with Forestry 3.

cfg file:
https://gist.github.com/Dream-Master/a528417b8cd5d1c6743a55e6a9a1ec59#file-cfg

**Comment by bdew** [comment]
Wait, you [have that file in overrides](https://github.com/GTNewHorizons/NewHorizons/blob/master/config/gendustry/overrides/recipes.cfg), right?

If so it will be loaded instead the [default config in the JAR](https://github.com/bdew/gendustry/blob/mc1710/resources/assets/gendustry/config/recipes.cfg#L228)  and the definitions in there. So anything that you want to keep need to be added to your override.

**Comment by Dream-Master** [comment]
The cfg file is in the overreide Folder allready. In the Main Folder are only the additional bees i add.

https://github.com/GTNewHorizons/NewHorizons/commit/3322575c1fd8117ba676ed78953e49cf13cb8e1c

https://github.com/GTNewHorizons/NewHorizons/tree/1.0.7.9/config/gendustry

**Comment by bdew** [comment]
Yes that's what i'm saying. Since it's in the override folder, it replaces the default config.

So if you want bees to still produce liquid DNA, you need to have those lines in your config.

To be clear does it work after you added that commit?

**Comment by Dream-Master** [comment]
Yes it work but i am not sure if you add more things. So i guess it never worked but no one complain in the pack.
I will move it out of the override folder and test it again. Thanks for clarification.

**Comment by Dream-Master** [comment]
Ok works now. Override Folder was the problem.
Thanks for finding it out.
