### ISSUE TITLE
Infinite covers 

### ISSUE THREAD

**Issue by Dijkstra1-zz** [bdew-minecraft/gendustry#158]
I have made genetic sampler put a input cover on side and a output cover on the over side, any when i went to move it gave me to the covers did nit think anything about until I placed it still had the cover on, at first I though it may be a rendering bug, then I mined it again got another set of covers and then I placed it again it still had the covers, you get the picture.

**Comment by bdew** [comment]
Are you using the latest version of Gendustry and BDLib? 

This sounds like a bug that was when i originally added covers, but it was fixed in 1.6.0

**Comment by Dijkstra1-zz** [comment]
Don't know I can check, which ever version ftb infinity is using. It will not be the first I will have to fix the pack if that is what it is.
