### ISSUE TITLE
Feature request : No Mutation Upgrade

### ISSUE THREAD

**Issue by MatthieuLepers** [bdew-minecraft/gendustry#159]
Hello ! This day when I'm try to get a spacific bee with Industrial apiary and I found a feature for your mod.

I drop Watery princess and Watery drone from Magic Bee into industrial apiary and the result can be a mutation of the two pure watery bee. I need for a 'No Mutation Upgrade'. This upgrade set the probability of mutating to 0.

Can you implement this upgrade ?
Community can help me to improve this feature ?

You're the mod maker, you can nerf this if you would (turn origin princess to ignoble princess for exemple or other ...)

**Comment by bdew** [comment]
I'm not sure i can actually force mutations to not happen with an upgrade, i'll look at forestry code that handles that part of the API when i have the chance.

At any rate, bees really shouldn't mutate when you breed 2 pure bees of the same species. What are they mutating into? It's most likely a bug in whatever adds that mutation.

**Comment by MatthieuLepers** [comment]
I got this mutation Watery + Watery = Aqua, this link (http://ftb.gamepedia.com/Watery_Bee).

I found this mutation is only possible if a special block is under apiary, sorry for disturbance.

I'm french and i've found few translate problem, i can send you a better translation for your mod ;)

**Comment by bdew** [comment]
Thanks for the translation update! :)
