### ISSUE TITLE
[Feature Request] Possibility to disable traits imprinting

### ISSUE THREAD

**Issue by JasonMcRay** [bdew-minecraft/gendustry#162]
Would it be possible to implement feature for the Imprinter to not allow changing specific traits on certain custom bees? (Changing traits via normal breeding would still be possible, just not forced imprinting)

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
