### ISSUE TITLE
Glitchy bee textures

### ISSUE THREAD

**Issue by absolutezero98** [bdew-minecraft/gendustry#164]
Hello guys,
I'm new here and currently playing the BeyondReality Modpack with Gendustry. A few days ago the textures from the Gendustry bees glitched out and had a chisel texture in them. I know that there is a similar post to this issue and I know that probably Thermal Foundation is the problem, but I can't remove this mod without also removing Thermal Expansion and Thermal Dynamics. Are there any other ways to solve this graphic problem. My English isn't that best so sorry for that ;-D

![2016-05-29_19 42 49](https://cloud.githubusercontent.com/assets/19637027/15635091/a19a81fa-25d5-11e6-8abf-d3616b1e3d61.png)

**Comment by bdew** [comment]
This was reported in #154.

Sadly i have no idea what causes it or how to fix it, i tried on multiple different systems and couldn't reproduce the bug.

If you have any more details or ideas please post them in the other issue.
