### ISSUE TITLE
Industrial apiaries don't work when chunkloaded and no players nearby

### ISSUE THREAD

**Issue by BarsikTheCaT** [bdew-minecraft/gendustry#167]
Recently I noticed that when I'm offline my bees don't even die and last for10-12 hours. The area is chunkloaded, the power supply is steady, but they still don't work. Tested with beehouses and apiaries - they work fine.

**Comment by bdew** [comment]
What are you using for chunkloading?

**Comment by BarsikTheCaT** [comment]
Tried both world anchor and admin anchor from railcraft

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
