### ISSUE TITLE
FlowerAllele Spread does not spread block

### ISSUE THREAD

**Issue by leagris** [bdew-minecraft/gendustry#172]
Hello @bdew 

I can not get bees to spread block configured with custom FlowerAllele

The example here does not spread gold ores:
https://github.com/bdew/gendustry/blob/mc1710/example_configs/example_bees.cfg#L72

Using:
- gendustry-1.6.4.135-mc1.7.10.jar
- forestry_1.7.10-4.2.10.905-unstable.jar
- forge 1614

**Comment by bdew** [comment]
Yes spreading was never finished in the 1.7.10 version. I will get it working in 1.10.2 soon(tm).

**Comment by leagris** [comment]
Any chance you can get it working for 1.7.10?
I'd like to make our BeyondReality Oil bee randomly spread `minecraft:fire` blocks.
This bee now needs Buildcraft Oil world fluid blocks as flower. This part works except those Gregtech Tile Ore blocks with NBT ore type)
But, given it is a bee to provide a renewable fuel source. It would be legit Nerf to have it also spread some fires while pollinating at those oil puddles. (Reward/Risk balance).

Here it is:

``` javascript
FlowerAllele oilBlocks {                // Allele UID will be gendustry.flowersOilBlocks (note the capitalization)
  Dominant
  Accepts B:"BuildCraft|Energy":blockOil, OD:oreOilSands, I:gregtech:"gt.blockores"@878, I:gregtech:"gt.blockores"@1878, I:gregtech:"gt.blockores"@2878, I:gregtech:"gt.blockores"@3878, I:gregtech:"gt.blockores"@4878 // List of Oil blocks that are accepted as "flowers"
  Spread B:minecraft:"fire" 1.0         // Shall spread fire
}
cfg Bees {
    cfg Oil {
        Dominant = No
        Glowing = Yes
        PrimaryColor = 0x4C4C4C
        SecondaryColor = 0x333333
        Secret = No
        Humidity = Arid
        Temperature = Warm
        Nocturnal = Yes
        Binominal = Oil
        Authority = BeyondReality
        Branch = "brbees.organic"
        Products = DropsList(
            30% I:Forestry:beeCombs@0 // Honey Comb
            )
        Specialty = DropsList(
            50% S:gendustry:"HoneyComb.oil"
            )
        cfg Traits {
            Base = "forestry.speciesModest"
            Humidity_Tolerance = "forestry.toleranceUp2"
            Temperature_Tolerance = "forestry.toleranceDown1"
            Flower_Provider = "gendustry.flowersOilBlocks"
            }
        }
    }
```

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
