### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Claycorp** [bdew-minecraft/gendustry#178]
http://pastebin.com/Gi7ijdtn

**Comment by bdew** [comment]
Version mismatch between BDLib and Gendustry. Make sure you are using the latest version of both mods.

**Comment by Claycorp** [comment]
It was installed via curse. If you mark versions improperly this will happen. Don't mark something as Beta then mark its required version as Alpha. Things get installed incorrectly then.

**Comment by bdew** [comment]
Everything is marked correctly on my side, you were using Gendustry 1.6.4.8 (beta) with BDLib 1.12.2.8 (latest alpha).

If you use the last beta for each, or the last alpha for each it would work correctly.

**Comment by Claycorp** [comment]
You or curse did something wrong because all I did was click the "Install" button on gendustry and it gave the improper versions.
