### ISSUE TITLE
Crash upon start up

### ISSUE THREAD

**Issue by erindal** [bdew-minecraft/gendustry#179]
http://pastebin.com/HrdetsHK

(forge-1.10.2-12.18.1.2066.jar)
(bdlib-1.12.2.8-mc1.10.2.jar)
(forestry_1.10.2-5.2.9.241.jar)
(gendustry-1.6.4.8-mc1.10.2.jar)

Full modlist is line 114 in the crash report, its not long. My game starts fine with the mod disabled.

I suspect it has something to do with a recent forestry update, I'm rolling back and testing.

**Comment by erindal** [comment]
Rolling back forestry didn't work.

**Comment by bdew** [comment]
Version mismatch between BDLib and Gendustry. Make sure you are using the latest version of both mods.

**Comment by erindal** [comment]
RIGHT. Stupid Curse. Thank you.
