### ISSUE TITLE
No Specialties?

### ISSUE THREAD

**Issue by mediocretes** [bdew-minecraft/gendustry#18]
I've got an industrial apiary set up with austere bees to exactly replicate the home biome conditions, and it is not producing specialties.  I was hoping that it would!

If this is intended behavior, just close this - it wasn't clear from the documentation whether or not I could expect powdery combs under this circumstance, but I was sure hoping.

**Comment by bdew** [comment]
I've looked into it and it seems to be a problem with how forestry checks for jubilance. It looks like it grabs the exact biome where the apiary is located and checks against that and ignores the modified temp/humidity values provided by the apiary.

I've reported it to Forestry bug tracker - https://bitbucket.org/sengir/forestry/issue/732/jubilancedefault-ignores-modified

I could possibly add some upgrades that override the biome like hell upgrade does now, need to think about it.

**Comment by bdew** [comment]
I've added some upgrades that override the biome at a significant cost in b1a50d1f138f2d3ca201c2bc6add6d7834111aa0, this should enable getting the specialty products for all forestry bees and hopefully most bees from other addons.

**Comment by mediocretes** [comment]
Wow, that was fast.  Thanks!

**Comment by mediocretes** [comment]
Also, your code is fun to read, and I love your mod.  You're probably also handsome and strong.  And, let's say, brave.
