### ISSUE TITLE
jei render issue 

### ISSUE THREAD

**Issue by tiarnia** [bdew-minecraft/gendustry#180]
getting this when looking in JIE using gen and scrolling down

 Description: Rendering screen
[B#347]  
[B#347]  java.lang.NullPointerException: Rendering screen
[B#347]     at net.bdew.gendustry.forestry.GeneSampleInfo.getLocalizedName(GeneSampleInfo.scala:59)
[B#347]     at net.bdew.gendustry.items.GeneSample$.func_77624_a(GeneSample.scala:56)
[B#347]     at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:610)
[B#347]     at mezz.jei.gui.ingredients.GuiItemStackFast.getTooltip(GuiItemStackFast.java:223)
[B#347]     at mezz.jei.gui.ingredients.GuiItemStackFast.drawTooltip(GuiItemStackFast.java:216)
[B#347]     at mezz.jei.gui.ItemListOverlay.drawTooltips(ItemListOverlay.java:360)
[B#347]     at mezz.jei.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:109)
[B#347]     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_669_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic)
[B#347]     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
[B#347]     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[B#347]     at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:383)
[B#347]     at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
[B#347]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
[B#347]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[B#347]     at net.minecraft.client.main.Main.main(SourceFile:124)
[B#347]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#347]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#347]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#347]     at java.lang.reflect.Method.invoke(Unknown Source)
[B#347]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#347]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#347]

**Comment by bdew** [comment]
Can't reproduce this.

What versions of JEI, Gendustry and Forestry?
