### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by quienti** [bdew-minecraft/gendustry#183]
Gendustry: 1.6.4.17, bdLib: 1.12.2.8, Forge: 12.18.1.2088

Same crash with last alpha release :/

[crash-2016-09-16_15.49.45-client.txt](https://github.com/bdew/gendustry/files/476983/crash-2016-09-16_15.49.45-client.txt)

**Comment by bdew** [comment]
Hm, that makes no sense to me. What is your client language set to?

**Comment by quienti** [comment]
I did not put the language because I never started this modpack, so en_US normally ?
There is a possibility to know what language is set ?

**Comment by quienti** [comment]
Okay, I have tried with minecraft launcher, and it works
(Yes, because I use my custom launcher), so I have a bug with my code apparently :/

Sorry, I search why is my fault !

Thank you for your help

**Comment by bdew** [comment]
If that helps you debugging, what i think happened is that LanguageManager.getCurrentLanguage returns null for some reason... Looking at the vanilla code i'm not sure how that would happen... Built-in resource pack failing to load maybe?

**Comment by quienti** [comment]
Actually, I do not know, but I will come back to you when I have found a solution with with strange bug...
Because, when I launch an official version, it works fine, but when I try with a modpack, crash...

**Comment by quienti** [comment]
Ok , I found my problem!
You were right, when I loaded Forge, I lacked the addition of " assets" in the JSON file -_-

Thank you for your help, you had given me the solution :D

Sorry for the inconvenience
