### ISSUE TITLE
[1.10.2] Bees in genetic sampler giving Cocoon: False gene

### ISSUE THREAD

**Issue by RealGrep** [bdew-minecraft/gendustry#184]
Not a huge issue, but having had bee hives when I was growing up, I'm fairly sure bees don't cocoon. Well, at least it's giving the "Cocoon: False" gene, which I suppose isn't wrong, strictly speaking. :)

However, I think this is unintended, particularly since it should never be True for bees anyway, nor did it do this in 1.7.10, so I assume this is a bug. Gotten it from multiple bees so far. The other ones were stock Forestry bees, but I forgot to note what bees they were. I did just get it for a Rocky bee from "More Bees".

This is with gendustry-1.6.4.20-mc1.10.2.jar and bdlib-1.12.2.12-mc1.10.2.jar, Forge 2086 in MC 1.10.2. Nothing in the logs of any use here, of course.

(Side note: Is it intended that I can't copy genes and templates in the Genetic Imprinter anymore? Shall I log an issue for that?)

And thanks a lot, it's glorious having this available in 1.10.2. Your work is highly appreciated (also love Advanced Generators).

**Comment by bdew** [comment]
I'm looking at the code and i don't really see how you could end up with a cocoon sample from bees. Are you sure that you didn't somehow end up sampling a butterfly? :P Does the sample say "Taken from a Bee" or "Butterfly"? 

> Side note: Is it intended that I can't copy genes and templates in the Genetic Imprinter anymore? Shall I log an issue for that?

There is a separate machine ([transposer](https://bdew.net/gendustry/genetic-transposer/)) for copying samples/templates. I'm pretty sure you never could copy them in imprinters. Or at least that wasn't intentional.

**Comment by RealGrep** [comment]
It does indeed say "Taken from a Bee". Case in point: https://www.dropbox.com/s/vlx9426annmio4p/BeeCocoonGene.png?dl=0

No idea how, but there it is, it's totally happening. XD

And glad I asked about the copying before filing a bug report. Wasn't sure if it was a bug or me. Turns out it's me. Hey, it happens! Thanks. :)

**Comment by RealGrep** [comment]
The NBT for that erroneous cocoon gene (false) for the bee, in case that helps at all: {species:"rootBees",chromosome:7,allele:"forestry.boolFalse"}

Metadata is 0.

Also note I do see the genes in JEI for Cocoon and with Taken from a Bee. They have true and false rather than what I see for butterflies, namely default and silk.

**Comment by bdew** [comment]
Oh derp! Looks like i had an error in my localization file. That sample is for "tolerates rain" but shows up as "cocoon". Should be fixed in next build.

**Comment by RealGrep** [comment]
Ahah! Ok, that makes sense. Glad you figured it out. <3
