### ISSUE TITLE
Any custom bee texture* overrides by other texture from any mod. HELP PLS

### ISSUE THREAD

**Issue by ieldan22** [bdew-minecraft/gendustry#185]
this is not problem with texture pack

**Comment by bdew** [comment]
Screenshot? Version?

**Comment by ieldan22** [comment]
Version: latest | Screenshot: http://imgur.com/gallery/NTz3B

**Comment by bdew** [comment]
Looking at the screenshot, i see Thermal Expansion icons on your creative tabs, so i'm going to assume this is some version for 1.7.10 rather than latest.

Do you have DragonAPI installed? It might be the same bug as #154.

Somebody reported that disabling the animated icon for blaze powder in config/cofh/thermalfoundation/client.cfg seems to fix it.

**Comment by ieldan22** [comment]
http://imgur.com/gallery/HyrMu
Sorry, not helped

This is a mod list:

```
**
```
- UCHIJAAAA mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
-   UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
-   UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
-   UCHIJAAAA   appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core](minecraft.jar) 
-   UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
-   UCHIJAAAA   ImmibisMicroblocks{59.1.0} [Immibis's Microblocks](ImmibisMicroblocks.jar) 
-   UCHIJAAAA   Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
-   UCHIJAAAA   NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
-   UCHIJAAAA   ThE-core{1.0.0.1} [Thaumic Energistics Core](minecraft.jar) 
-   UCHIJAAAA   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
-   UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
-   UCHIJAAAA   BinniePatcher{1.8.2} [Binnie Patcher](minecraft.jar) 
-   UCHIJAAAA   CoFHCore{1.7.10R3.1.3} [CoFH Core](CoFHCore-[1.7.10]3.1.3-327.jar) 
-   UCHIJAAAA   BuildCraft|Core{7.0.12} [BuildCraft](BuildCraft.jar) 
-   UCHIJAAAA   BuildCraft|Energy{7.0.12} [BC Energy](BuildCraft.jar) 
-   UCHIJAAAA   IC2{2.2.782-experimental} [IndustrialCraft 2](ic2_exp.jar) 
-   UCHIJAAAA   GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore.jar) 
-   UCHIJAAAA   SpaceCore{4.1.9} [4Space Core](4Space-4.1.9.jar) 
-   UCHIJAAAA   ExoCore{0.1.2} [4Space Exoplanets Core](4Space-4.1.9.jar) 
-   UCHIJAAAA   ExoElipse{0.1.2} [4Space Exoplanets Elipse](4Space-4.1.9.jar) 
-   UCHIJAAAA   SpaceCallisto{4.1.9} [4Space Callisto](4Space-4.1.9.jar) 
-   UCHIJAAAA   SpaceEuropa{4.1.9} [4Space Europa](4Space-4.1.9.jar) 
-   UCHIJAAAA   SpaceVenus{4.1.9} [4Space Venus](4Space-4.1.9.jar) 
-   UCHIJAAAA   SpaceIo{4.1.9} [4Space Io](4Space-4.1.9.jar) 
-   UCHIJAAAA   SpaceMercury{4.1.9} [4Space Mercury](4Space-4.1.9.jar) 
-   UCHIJAAAA   SpacePluto{4.1.9} [4Space Pluto](4Space-4.1.9.jar) 
-   UCHIJAAAA   customtweaks{1.0.0} [ExtrabiomesXL]([1.7.10]_CustomTweaks.zip) 
-   UCHIJAAAA   BuildCraft|Factory{7.0.12} [BC Factory](BuildCraft.jar) 
-   UCHIJAAAA   BuildCraft|Transport{7.0.12} [BC Transport](BuildCraft.jar) 
-   UCHIJAAAA   BuildCraft|Silicon{7.0.12} [BC Silicon](BuildCraft.jar) 
-   UCHIJAAAA   additionalpipes{4.7.0} [Additional Pipes](AdditionalPipes.jar) 
-   UCHIJAAAA   AdvancedMachines{1.1.6} [IC2 Advanced Machines Addon](AdvancedMachinesAS-1.7.10.jar) 
-   UCHIJAAAA   AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) 
-   UCHIJAAAA   alluwant{2.1} [All U Want](All-U-Want 2.1.jar) 
-   UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI_1.7.10_1.2.4.jar) 
-   UCHIJAAAA   appliedenergistics2{rv3-beta-6} [Applied Energistics 2](appliedenergistics2-rv3-beta-6.jar) 
-   UCHIJAAAA   MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
-   UCHIJAAAA   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft_1.7.10_4.2.3.5 %282%29.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
-   UCHIJAAAA   Automagy{0.28.2} [Automagy](Automagy-1.7.10-0.28.2.jar) 
-   UCHIJAAAA   bdlib{1.9.4.109} [BD Lib](bdlib-1.9.4.109-mc1.7.10.jar) 
-   UCHIJAAAA   BiblioCraft{1.11.2} [BiblioCraft](Bibliocraft.jar) 
-   UCHIJAAAA   ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.5-115.jar) 
-   UCHIJAAAA   ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.4-247.jar) 
-   UCHIJAAAA   BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A %281%29.jar) 
-   UCHIJAAAA   ExtrabiomesXL{3.16.2} [ExtrabiomesXL](ExtrabiomesXL.jar) 
-   UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
-   UCHIJAAAA   Natura{2.2.0} [Natura](natura-1.7.10-2.2.0-b1.jar) 
-   UCHIJAAAA   Forestry{4.2.15.63} [Forestry for Minecraft](forestry_1.7.10-4.2.15.63.jar) 
-   UCHIJAAAA   BinnieCore{2.0-pre14} [Binnie Core](binnie-mods-2.0-pre14.jar) 
-   UCHIJAAAA   Botany{2.0-pre14} [Botany](binnie-mods-2.0-pre14.jar) 
-   UCHIJAAAA   ExtraBees{2.0-pre14} [Extra Bees](binnie-mods-2.0-pre14.jar) 
-   UCHIJAAAA   ExtraTrees{2.0-pre14} [Extra Trees](binnie-mods-2.0-pre14.jar) 
-   UCHIJAAAA   Genetics{2.0-pre14} [Genetics](binnie-mods-2.0-pre14.jar) 
-   UCHIJAAAA   BuildCraft|Builders{7.0.12} [BC Builders](BuildCraft.jar) 
-   UCHIJAAAA   BuildCraft|Robotics{7.0.12} [BC Robotics](BuildCraft.jar) 
-   UCHIJAAAA   chisel{1.5.6b} [Chisel](Chisel-Mod-1.7.10.jar) 
-   UCHIJAAAA   colorblocks2{2.0} [ColorBlocks 2](colorblocks2-2.0.jar) 
-   UCHIJAAAA   ComputerCraft{1.75} [ComputerCraft](ComputerCraft1.75.jar) 
-   UCHIJAAAA   TeNNoX_CustomSelectionBox{1.3} [CustomSelectionBox](CustomSelectionBox-1.7.10-1.3.jar) 
-   UCHIJAAAA   EMT{1.2.6.1} [Electro-Magic Tools](ElectroMagicTools-1.2.6.1[1.7.10].jar) 
-   UCHIJAAAA   enviromine{1.2.23} [EnviroMine](enviromine-[1.7.10].jar) 
-   UCHIJAAAA   exnihilo{1.38-49} [Ex Nihilo](Ex-Nihilo-1.38-49.jar) 
-   UCHIJAAAA   extracells{2.2.35} [ExtraCells](ExtraCells-1.7.10-2.2.35b61.jar) 
-   UCHIJAAAA   harvestcraft{1.7.10d} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10f.jar) 
-   UCHIJAAAA   TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct](TConstruct-1.7.10-1.8.5 %281%29.jar) 
-   UCHIJAAAA   ExtraTiC{1.4.6} [ExtraTiC](ExtraTiC-1.7.10-1.4.6.jar) 
-   UCHIJAAAA   GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets.jar) 
-   UCHIJAAAA   GraviSuite{1.7.10-2.0.1} [Graviation Suite](GraviSuite-1.7.10-2.0.1.jar) 
-   UCHIJAAAA   Highlands{2.2.0} [Highlands](Highlands-Mod-1.7.10.jar) 
-   UCHIJAAAA   HardcoreQuesting{4.4.4} [Hardcore Questing Mode](HQM-The Journey-4.4.4.jar) 
-   UCHIJAAAA   IC2NuclearControl{2.3.1a-Butt} [Nuclear Control 2](IC2NuclearControl-2.3.1a-Butt.jar) 
-   UCHIJAAAA   ImmibisCore{59.1.1} [Immibis Core](ImmibisCore.jar) 
-   UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
-   UCHIJAAAA   JABBA{1.1.4} [JABBA](jabba.jar) 
-   UCHIJAAAA   lootplusplus{0.24_for_1.7} [Loot++](Loot++-0.24_for_1.7.jar) 
-   UCHIJAAAA   Railcraft{9.3.3.0} [Railcraft](Railcraft_1.7.10-9.3.3.0.jar) 
-   UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
-   UCHIJAAAA   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer_2.5_1.7.10_164 %282%29.jar) 
-   UCHIJAAAA   MagicBees{1.7.10-2.4.0} [Magic Bees](MagicBees.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MrTJPCoreMod{1.1.0.33} [MrTJPCore](MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
-   UCHIJAAAA   ProjRed|Core{4.7.0pre12.95} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
-   UCHIJAAAA   ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UCHIJAAAA   MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) 
-   UCHIJAAAA   Mystcraft{0.12.3.03} [Mystcraft](mystcraft-1.7.10-0.12.3.03.jar) 
-   UCHIJAAAA   NEIAddons{1.12.11.36} [NEI Addons](NEIAddons.jar) 
-   UCHIJAAAA   NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools](NEIAddons.jar) 
-   UCHIJAAAA   NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2](NEIAddons.jar) 
-   UCHIJAAAA   NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany](NEIAddons.jar) 
-   UCHIJAAAA   NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry](NEIAddons.jar) 
-   UCHIJAAAA   NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables](NEIAddons.jar) 
-   UCHIJAAAA   NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo](NEIAddons.jar) 
-   UCHIJAAAA   neiintegration{1.0.13} [NEI Integration](NEIIntegration-MC1.7.10-1.0.13.jar) 
-   UCHIJAAAA   pixelmon{3.5.0} [Pixelmon](Pixelmon-Universal.jar) 
-   UCHIJAAAA   ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
-   UCHIJAAAA   ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
-   UCHIJAAAA   ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
-   UCHIJAAAA   ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
-   UCHIJAAAA   ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication](ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
-   UCHIJAAAA   ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
-   UCHIJAAAA   ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
-   UCHIJAAAA   qmunitylib{1.0} [QmunityLib](QmunityLib.jar) 
-   UCHIJAAAA   ReiMinimap{1.7.10} [Rei's Minimap](ReisMinimap.jar) 
-   UCHIJAAAA   SC0_SpaceCore{0.7.8} [SpaceCore](SpaceCore-1.7.10.jar) 
-   UCHIJAAAA   thaumcraftgates{1.4.2} [Thaumcraft Gates](TaumicGates.jar) 
-   UCHIJAAAA   tcinventoryscan{1.0.11} [TC Inventory Scanning](tcis.jar) 
-   UCHIJAAAA   thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
-   UCHIJAAAA   thaumicenergistics{1.0.0.5} [Thaumic Energistics](thaumicenergistics-1.0.0.5.jar) 
-   UCHIJAAAA   ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.2.0-171.jar) 
-   UCHIJAAAA   TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
-   UCHIJAAAA   UnicodeFontFixer{1.1.4-mc1.7.10} [UnicodeFontFixer](UnicodeFontFixer-1.1.4-mc1.7.10.jar) 
-   UCHIJAAAA   Unifier{1.9} [Unifier](Unifier-1.7.10-1.9.jar) 
-   UCHIJAAAA   WailaHarvestability{1.1.5} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.5.jar) 
-   UCHIJAAAA   worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
-   UCHIJAAAA   WorldEditCUI{1.7.2_02} [WorldEditCUI](WorldEditCUI-[1.7.10].jar) 
-   UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
-   UCHIJAAAA   ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
-   UCHIJAAAA   MCFrames{1.0} [MCFrames](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
-   UCHIJAAAA   RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
-   UCHIJAAAA   IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](IguanaTweaks-TConstruct.jar) 
-   UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
-   UD  MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UD  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UD  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
-   UD  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar)

*\*

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
