### ISSUE TITLE
Significant mutagen loss with fluid pipes (1.6.4)

### ISSUE THREAD

**Issue by jalapeno777** [bdew-minecraft/gendustry#19]
In doing a quick video tutorial I noticed a pretty nasty mutagen loss bug when attached a fluid conduit to a mutagen producer that already has mutagen in it.

Here's a quick 1 minute video showing the bug in action where there were 9000mb in the mutagen producer but after fixing a fluid conduit to it, all 9000mb was removed but only 200mb actually was transferred.

This is using the following mods:

BDLib: 1.2.0.38
Gendustry: 1.1.0.61
EnderIO: 1.0.1.353

http://youtu.be/Vq3F2lF4cdc

**Comment by jalapeno777** [comment]
I was wrong, the loss is still there but it's not just from placing the conduit after the mutagen is there...it seems to only ever transfer 200mb at a time but still wipe out all excess that was in the tank at the time.  So whether I have 200mb or 10,000mb...only 200mb is ever transferred and the rest disappears.

**Comment by bdew** [comment]
I see the problem, it happens because EnderIO messes up the FluidStack representing my internal tank. I'm tracing where exactly the problem is in EnderIO to submit a bug to CP and will release a version with a workaround from my side ASAP.
