### ISSUE TITLE
Custom Hives don't have a model

### ISSUE THREAD

**Issue by chazwarp923** [bdew-minecraft/gendustry#191]
Forestry Version: 5.2.14.270
Gendustry Version: 1.6.4.23

When adding a custom hive it has no in-game model, and therefore, no texture.
Ive attached all my custom config files just in case I'm doing something wrong somewhere.

[CustomBees.zip](https://github.com/bdew/gendustry/files/540487/CustomBees.zip)

**Comment by bdew** [comment]
The custom hives system is unfinished in 1.10 (that's one of the main reasons the mod is still in beta).
Right now you need to provide your own models and textures using either a resource pack or putting them in the JAR.

I'm planning to add access to premade models/textures with options to recolor them and if i can get that to work correctly - loading models from the config folder... but that's unfinished for now.

**Comment by chazwarp923** [comment]
Okay, thanks for the quick reply. If you need help testing anything just ask, I'd be more than happy to help.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
