### ISSUE TITLE
[1.10.2] [Enhancement] Search integration for samples in RFtools/EnderIO Storage networks (Probably more too)

### ISSUE THREAD

**Issue by MrNinja93** [bdew-minecraft/gendustry#192]
Just something I've come across in playing around with Gendustry, it can be a pain to find a specific trait sample in inventories. I hoped I could get around that in the EnderIO inventory panel system Or rftools storage module and just using the search bar to quickly locate the sample (e.g type effect to only see effect samples etc) but neither mods search bar works for them (They at-least show them as combined stacks to make removing un-needed dupes easier though!)

**Comment by bdew** [comment]
Hm i think i'll just put the name of the allele in the item name, that way everything will be able to search for them...

**Comment by MrNinja93** [comment]
That could work, though I guess that might take a rewrite of a few files to work with the new naming scheme.
