### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by wolfe02** [bdew-minecraft/gendustry#194]
http://pastebin.com/BbLHj3sH ( Crash Report)

get this when tryying to add bee

http://pastebin.com/KznhZ3Bg(New Bee)

**Comment by bdew** [comment]
There are some small changes to the format in 1.10, i haven't gotten around to documenting them yet but you can see the updated examples here: https://github.com/bdew/gendustry/tree/mc1.10.2/example_configs

Change this 

> 25% S:gendustry:"HoneyComb.Apat"

to 

> 25% HoneyComb:Apat

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
