### ISSUE TITLE
Config change "NEI" to "JEI"

### ISSUE THREAD

**Issue by MrNinja93** [bdew-minecraft/gendustry#195]
In the middle of updating private pack and going through configs and saw Gendustry listing "nei" in the config for recipe enabling considering JEI has taken over for 1.10 it may confuse people. (Or maybe as NEI is now a 1.10 thing simply add NEI/JEI if you support both internally.)  

https://github.com/bdew/gendustry/blob/mc1.10.2/src/net/bdew/gendustry/config/Config.scala

**Comment by bdew** [comment]
Those options currently do nothing anyway. I still need to re-write the recipe display code to work with JEI (and will change them to match once i do).

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
