### ISSUE TITLE
Add Config Option to hide stuff in JEI.

### ISSUE THREAD

**Issue by UnPure** [bdew-minecraft/gendustry#196]
Hey there.
I would like to ask if there is any chance to see an option to hide all the different Templates in JEI.
I like it to have a clean JEI without stuff thats not realy needed in there.
The default template is enough, i think there is no need for all the filled ones.
Its possible to hide the samples in JEI, but not the templates because they are basically all the same item.
I also tried to hide them with minetweaker/crafttweaker but the data is too long.
I realy would like to see a config option to hide ever filled template.
Or maybe just split the empty template to a different item so it would be possible to hide the rest with JEI's feature. Like with the gene sample. Its possible to hide all the filled ones without hiding the empty one.

**Comment by bdew** [comment]
I'll add it when i actuall get JEI support done, which will hopefully be soon(tm).

**Comment by UnPure** [comment]
Thats ok, thank you! :)

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
