### ISSUE TITLE
[Minor Bug] Pollen Collection Kits not working anymore

### ISSUE THREAD

**Issue by Garonne** [bdew-minecraft/gendustry#197]
Something changed in recent version(s) of Forestry. Pollen Collection Kits don't work anymore (based on Forestry 5.2.16.321)

Oops... Wait a sec. Rechecking... **Wasn't running most recent versions** of Gendustry & BdLib...

**Comment by Garonne** [comment]
Dang... Updating Gendustry & BdLib crashed my game (crash was BdLib I think...)

**Comment by bdew** [comment]
Hm, looks like something broke. Will look into it.

**Comment by bdew** [comment]
Should be fixed in next build
