### ISSUE TITLE
[1.10.2] Butterfly gendustry:geneSample Nocturnal:boolTrue missing

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [bdew-minecraft/gendustry#198]
After extensive breeding of bees and extraction of gene samples I am able to extract both nocturnal bool traits from bees. Butterflies, however, despite attempts with primary or secondary traits having nocturnal TRUE I have not been able to extract Nocturnal:boolTrue from ANY butterfly. Even hybrid butterflies will extract secondary traits on occasion EXCEPT for nocturnal:true. A quick search in JEI FAILS to reveal any Nocturnal:true butterfly sample/template. 

edit: versions

forge 2107
Forestry 5.2.14.267
Gendustry 1.6.4.21
JEI 3.12.4.294

**Comment by bdew** [comment]
The way nocturnal works is kinda funny, and it's name isn't entirely correct.

Both bee and butterfly species have a "nocutrnal" flag. This flag is hardcoded in the species and is not part of the genetics system (you can't change it through breeding, samples, etc.) If it's true - the bee/butterfly will work in the night and not sleep in the day.

The nocturnal allele allows the bee/butterfly to work during the other half of the day. For bees it was actually renamed to "never sleeps" in recent versions of forestry, which matches what it really does more closely.

The reason you don't see it in JEI and can't get it from sampling is that no forestry butterflies actually have it (the list you see is built from the templates of all registered species). 

There are some butterflies (technically they are all moths, i think) that have the nocturnal flag set, but none have the actual allele.

**Comment by bdew** [comment]
Oh yeah and if you want to play with it you can spawn the sample with

> /givesample rootButterflies nocturnal forestry.boolTrue

You need to be OP or have cheats enabled.

**Comment by Rumpelstiltskinny** [comment]
hmm, interesting that Nocturnal would be hardcoded. So be it. Guess it's oversight on Forestry's part and nothing lacking in Gendustry. Great mod bdew, thanks.
