### ISSUE TITLE
Custom centrifuge recipe does not appear to work in SMP, works fine in SSP

### ISSUE THREAD

**Issue by utoc** [bdew-minecraft/gendustry#201]
So, my setup is likely at fault here because I suspect the way I am trying to get the power modules to drop is probably not the way you intended.

My config:

```
recipes {

centrifuge: I:morebees:CombWither, 10 cycles => {
                80% I:forestry:refractoryWax
                90% I:minecraft:bone
                90% I:minecraft:coal
                25% I:gendustry:PowerModule
            }
}
```

I am simply hijacking an existing comb from MoreBees mod to give it an additional drop.  This works great in SSP but doesn't work in SMP.

If there is an alternative way of going about this or some kind of debugging I can do for you, let me know!

Running: bdlib-1.12.2.18-mc1.10.2.jar, gendustry-1.6.4.25-mc1.10.2.jar, forestry_1.10.2-5.2.16.327.jar and fml build 2151 for 1.10.2

Thanks!

**Comment by bdew** [comment]
This should work... when it doesn't work in SMP are you sure you are putting the files in the right place on the server? If you still can't figure it out upload the log from the server somewhere.

**Comment by utoc** [comment]
Whats interesting is that when I tested this when adding it to the pack, it worked fine.  Now that I'm re-testing in SSP and SMP, it is not fine and not working in either.

The SMP config is located at ` config/gendustry/custombees.cfg` which is the same place its loaded for SSP

Server log here: https://gist.github.com/utoc/775d3ebad12f6a59c021c30fae6257b5

JEI shows the drop with a 25% chance rate in both SMP and SSP - http://i.imgur.com/qDZEz0p.png

Is it because I am using an existing comb?  IF that is the case, can I make an existing queen, like the tropical for example, drop a second comb as an alternative.. I know your configs are capable of doing it but is that valid or will it cause similar weirdness to what I'm seeing here?

**Comment by bdew** [comment]
Looks like i've misread the original issue, after seeing that JEI screenshot that makes more sense.

What's happening is that you're getting a duplicate centrifuge recipe for that comb - both the original and the modified, and whichever one ends up being used probably depends on load ordering / luck / alignment of the stars :P

You can't currently modify an existing queen's drops, and adding something like that is problematic with forestry API.

I'll add something to extend/replace existing centrifuge/squeeze recipes.

**Comment by bdew** [comment]
New build should be up shortly, with it you can do the following which will add the drop list to the existing recipe.

    recipes {
        centrifuge: ADD I:morebees:CombWither => {
            25% I:gendustry:PowerModule
        }
    }

Note that you don't specify cycles with this version of the statement (as it comes from the original recipe).

You could also use REPLACE to completely replace the existing recipe, eg.:

    recipes {
        centrifuge: REPLACE I:morebees:CombWither, 10 cycles => {
            80% I:forestry:refractoryWax
            90% I:minecraft:bone
            90% I:minecraft:coal
            25% I:gendustry:PowerModule
        }
    }

**Comment by utoc** [comment]
Thank you, bdew!
