### ISSUE TITLE
Custom Bee doesn't drop Custom Drops

### ISSUE THREAD

**Issue by ErosM** [bdew-minecraft/gendustry#203]
Hi, 

I was trying to add some custom bee with custom drops to FTB HermitPack. I successfully added some new species dropping items in the pack (osmium, apatite), but I'm not able to set custom drops of combs and honeydrops. I can see them in JEI (with I:.., not with S:...), but there is no crafting recipe and the bees don't drop those items.

When I use S:... minecraft crashes. In the crashlog it says 

Description: Gendustry config loading failed in file /home/eros/ftb/FTBPresentsHermitPack/minecraft/config/gendustry/ExtraBees.cfg: Config parsing failed at 178.13: `[' expected but `:' found

Here is the fragment of code that fails:

```
cfg Steamy{
	    Dominant = Yes              
            Glowing = No           
            PrimaryColor = 0x4e4949      
            SecondaryColor = 0x807d7d
            Secret = No                    
            Humidity = Normal             
            Temperature = Normal           
	    Nocturnal = No               
            Binominal = Steamy          
            Authority = OnePunchPanda
            Branch = "gendustry.custom"
            Products = DropsList(                 
                30% S:gendustry:"HoneyComb.Steamy"
            )
            Specialty = DropsList(
	    	10% S:gendustry:"HoneyDrop.Steamy"
            )                 
            cfg Traits {
		Base = "forestry.speciesVindictive"
                Effect = "forestry.effectIgnition"
            }
}

cfg HoneyCombs{
	cfg Steamy{
		ID = 2500
		PrimaryColor = 0x4e4949
		SecondaryColor = 0x807d7d	
	}
}

cfg HoneyDrops{
	cfg Steamy{
		ID = 2500
		PrimaryColor = 0x4e4949
		SecondaryColor = 0x807d7d
	}
}

recipes {
	centrifuge: S:gendustry:"HoneyComb.Steamy", 10 cycles => 
	{
		30% S:gendustry:"HoneyDrop.Steamy"
		20% I:Forestry:beeswax@0
	}
	squeezer: S:gendustry:"HoneyDrop.Steamy", 20 cycles => steam 50mb
	mutation: 25% "forestry.speciesDemonic" + "forestry.speciesIndustrious" => "gendustry.bee.Steamy"
}
```

How can I solve this?

Thanks for your help

**Comment by bdew** [comment]
"S:" is removed in 1.10 (the underlying forge registry is gone).

Instead use "HoneyComb:Steamy" and "HoneyDrop:Steamy".

See the updated examples here:
https://github.com/bdew/gendustry/blob/mc1.10.2/example_configs/example_bees.cfg#L37

**Comment by ErosM** [comment]
Thank you very much, it worked perfectly. 

Keep the good work and have a nice day.
