### ISSUE TITLE
Can't add seed oil recipe

### ISSUE THREAD

**Issue by ErosM** [bdew-minecraft/gendustry#204]
Hi,

sorry to bother you again, but I have another issue.

I'm trying to add a squeezer recipe for seed oil. Using /dumpregistry I found that there are 2 choices for seed oil:

forestry:fluid.seed.oil (blocks section)
seed.oil (fluids section)

Neither works for me. I wrote the code like this:

`squeezer: HoneyDrop:Seedy, 20 cycles => B:forestry:fluid.seed.oil 250mb
`
or
`squeezer: HoneyDrop:Seedy, 20 cycles => seed.oil 250mb
`

I also tried  with quotes, without "B:...", seedoil and many others, but I always get the following message:

`Description: Gendustry config loading failed in file /home/eros/ftb/FTBPresentsHermitPack/minecraft/config/gendustry/ExtraBees.cfg: Config parsing failed at 291.44: string matching regex `-?\d+' expected but `:' found`

What do I do wrong?

Thanks for your help and time

**Comment by bdew** [comment]
Try this, i think it should work:

> squeezer: HoneyDrop:Seedy, 20 cycles => "seed.oil" 250mb

The fluid id needs to be quoted if it contains non-alphanumeric characters.

**Comment by ErosM** [comment]
Thanks it totaly worked. I thought I've tried that too... maybe I did it with the forestry block and not with seed.oil

Thanks again for you're help. Have a nice day
