### ISSUE TITLE
Industrial Apiary Ticking Block Crash

### ISSUE THREAD

**Issue by Hibernating-Bear** [bdew-minecraft/gendustry#205]
Upon having a Queen of any bee inside an Industrial Apiary it causes a crash, showing as a Ticking Block Entity Crash

Crash report can be found at http://pastebin.com/uZFbbT42

If you need any info let me know

**Comment by bdew** [comment]
Yay forestry breaking API again....

https://github.com/ForestryMC/ForestryMC/commit/7b1aead339d118f2e73798b5a62307d27b76d287

Fix incoming.

**Comment by bdew** [comment]
Should be fixed in this build: https://jenkins.bdew.net/job/gendustry-1.10.2/27/artifact/build/libs/gendustry-1.6.5.27-mc1.10.2.jar
