### ISSUE TITLE
Custom config file not loaded and causes crash

### ISSUE THREAD

**Issue by XxMrSpacexX** [bdew-minecraft/gendustry#206]
I was playing on my Sky Factory 2.5 instance (i added some mods to it) and i decided to add some custom bees to produce Draconium and Awakened Draconium, i followed the github examples and i thought i did everything right, but the game crashes at the start :(
Here are the logs: (i uploaded fml-client-1,2,3 and latest, i don't which i should be report, sorry)
fml-client-1: [https://hostr.co/jlu6GfphlKOk](url)
fml-client-2: [https://hostr.co/DdC8JxtWxeJP](url)
fml-client-3: [https://hostr.co/mYKdbVXS6uv6](url)
fml-latest: [https://hostr.co/aVCU3Wd08IxS](url)
Here are my gendustry custom files:
custombees.cfg: [https://hostr.co/x7JitGAVo8SR](url)
custombees.en_US.lang: [https://hostr.co/GPmBrb2i2n2I](url)
And here is the crash report: (one of many, but they are all similar)
[https://hostr.co/5Poa7jksq5C0](url)
i wish to have done everything correctly, if not, report me please
PS: sorry if my english isn't so good

**Comment by bdew** [comment]
The error message is very clear:

> Gendustry config loading failed in file D:\Documents\Curse\Minecraft\Instances\FTB Presents SkyFactory 2.5 (2)\config\gendustry\custombees.cfg: Config parsing failed at 13.3: `}' expected but `{' found

You have an extra curly bracket on line 13.

> cfg Draconist {
> **{** Dominant = No

There are also other random braces on lines 30, 33 and 50 that probably shouldn't be there.

**Comment by XxMrSpacexX** [comment]
err.. i uploaded the wrong file, that's an old one, this is the one that should work, but it doesn't:
[https://hostr.co/KonLZr1ejMhe](url)
i wrote this almost copying another custom file found on internet, that instead works fine
EDIT: and this is the correct crash report:
https://hostr.co/3oCx6rDmvrCe

**Comment by bdew** [comment]
> Config parsing failed at 52.13: `{' expected but `D' found

Error is on line 52....

> cfg Master Draconist 

You can't have spaces inside section names.

**Comment by XxMrSpacexX** [comment]
thank you! that's exactly what i wasn't able to understand...
i'm sorry to have wasted you time
