### ISSUE TITLE
[1.10.2] Server crash when putting bees in industrial apiary

### ISSUE THREAD

**Issue by beaussan** [bdew-minecraft/gendustry#207]
Hi, 

So there is a bug in gendustry with bees, I have no idea how the bug was produce, I wasen't on the server and the user who made this diden't remember how it worked.

Apparently, he manage to put a bee in one, but when trying to put one on another apiary, it crashed the server...*

It appends on the Resonant Rise b1.0.1 if you want the same environement.

Here is the crash log : 
https://gist.github.com/beaussart/428195ea2faff4842e9476f9a39cafdc

**Comment by bdew** [comment]
Forestry >= 5.2.16.337 has an incompatible API change. Update Gendustry to 1.6.5.27.

**Comment by beaussan** [comment]
Thank you ! Sorry for the incinveignance
