### ISSUE TITLE
Industrial Apiary ticking entity crash 1.10.2

### ISSUE THREAD

**Issue by indygwyn** [bdew-minecraft/gendustry#208]
Industrial Apiary eating my bees and upgrades, I have a feeling it's probably because I changed my forge.cfg to get it to stop crashing the entire server when I put a bee in an Industrial Apiary
    B:removeErroringEntities=true
    B:removeErroringTileEntities=true
But without those options in I get a complete crash when I put a bee in.  Happy to help debug.  I still have the crash reports from the Ticking block entity crashes.
http://pastebin.com/7Sy9JXHL

FTB Infinity Lite 1.4.1 SMP
Gendustry 1.6.4.24
Forestry 5.2.16.340

**Comment by bdew** [comment]
Forestry >= 5.2.16.337 has an incompatible API change. Update Gendustry to 1.6.5.27.
