### ISSUE TITLE
Automatic Extract Genetic Template from Genetic Replicator

### ISSUE THREAD

**Issue by MokuJinJin** [bdew-minecraft/gendustry#209]
I would like to automise crafting bees with AE2. 
I have extra cells, which add AE2 fluid, so Replicator is always full with protein and DNA.
I've a craft pattern to import genetic template into Replicator, and the resultant bee is exported with enderIO item conduit.

I've tried export cover, enderIO item conduit in extract mode, pipes, nothing can extract the template i put in the replicator.
With my setup, full of fluids, the replicator produce bees, tons of them since i cannot pull the template.

Gendustry 1.6.0.125
AE2 rv2-stable-10
Ender IO 1.7.10-2.3.0.422-beta

Mod pack FTB Infinity 2.3.5

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
