### ISSUE TITLE
1.11 Crash during startup

### ISSUE THREAD

**Issue by OrdinatorStouff** [bdew-minecraft/gendustry#212]
NullPointerException
net.bdew.gendustry.misc.ResourceListener$.func_110549_a(ResourceListener.scala:35)

http://pastebin.com/y4xGQrmf
gendustry-1.6.5.4-mc1.11.2.jar

This was reported to us on the AllTheMods discord by user @Minicrash5#1277 after downloading a fresh profile of AllTheMods 2 pack version 0.47 (clean install)

User got this crash repeatedly every startup. When gendustry removed, pack would load/start with no errors.

User **is** able to load AllTheMods 1 that also has gendustry but 1.10 version.

**Comment by bdew** [comment]
Hm i can't reproduce this with a clean download of ATM2 0.47.

Also the crash doesn't make sense, it looks like the current language in the client is set null which should never be.

Can you get the user to verify/redownload everything (maybe some corrupted file is messing things up), and if it still happens see if he has any weird settings or something else special about his setup?

I could probably just catch the NPE there and prevent it from crashing, but stuff will be broken everywhere if the language is broken.

**Comment by OrdinatorStouff** [comment]
User now states pack is working, including gendustry (possibly after forge update/version change or just updating modpack version again). Since no-longer happening suggest close this issue if no further action needed on our end. Not sure if you want to patch for that NPE just in case anyway. ¯\\\_(ツ)\_/¯

My other notes just for thoroughness:  
- I couldn't reproduce on my system either.
- User says OS language is English (i.e. not an obscure OS language bug or weird settings that I can tell)
- I had him re-download from curse a brand new profile (thinking the same; perhaps corrupt file/etc), and crash happened the same every time.
- Removing Gendustry let pack launch and enter world without crash. Re-adding gendustry restarted crashes again.

**Comment by BTernaryTau** [comment]
Just had this issue with the DW20 1.12 pack. I was able to resolve it by changing the language from "en_us" to "en_US".
