### ISSUE TITLE
crash on server startup(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [bdew-minecraft/gendustry#213]
bdlibe: bdlib-1.13.1.4-mc1.11.2
gendustry: gendustry-1.6.5.4-mc1.11.2
forge:1.11.2-2233
crash report:
[crash-2017-02-20_10.12.12-server.txt](https://github.com/bdew/gendustry/files/787853/crash-2017-02-20_10.12.12-server.txt)

**Comment by SDUBZ** [comment]
it seems like this could be related to bdlib itself,because it also crashed with just pressure pipes

**Comment by bdew** [comment]
> Caused by: java.lang.ClassNotFoundException: scala.util.parsing.combinator.JavaTokenParsers

Your install is borked. This class should be in the libraries installed by forge. Try redownloading/reinstalling in case something got corrupted.

If you used any third party tool to setup the server - report this to it's authors.

**Comment by SDUBZ** [comment]
yeah maybe it got missed due to my net being over congested and causing ym upload to turrn to crap sorry man :/

**Comment by SDUBZ** [comment]
and tank you for your help i was confused when it loaded on server on pc but not actual server :D

**Comment by bdew** [comment]
If that helps, the missing file you are looking for should be called scala-parser-combinators_2.11-1.0.1.jar
