### ISSUE TITLE
Mutagen Producer not producing

### ISSUE THREAD

**Issue by Anamatopeia** [bdew-minecraft/gendustry#214]
On 11.2, the Mutagen Producer never appears to process the resources into mutagen; the arrow never shows more than 0% progress. Have checked with Redstone (blocks and dust) and glowstone. Occurs both when newly connected to power and when internal power buffer is full.

**Comment by bdew** [comment]
Should be fixed in this build: https://minecraft.curseforge.com/projects/gendustry/files/2386590
