### ISSUE TITLE
Advanced Mutarton issue (wont breed)

### ISSUE THREAD

**Issue by kzintiwife** [bdew-minecraft/gendustry#215]
I get the advanced mutatron filled with rf, mutagen, labware, cultivated princess, and common drone.  I see Noble queen and Diligent queen.  Click on diligent queen and the squre changes colors,   and.... nothing. i can still click on the noble queen and same thing. i've tried click and drag, right click, shift right click...   What am I missing?  all the spotlights just are like oh and here is the advanced, and move on.  using the latest gendustry for 1.11.2 and forestry 1.11.2-5.3.1.49

![bees](https://cloud.githubusercontent.com/assets/24585859/23592413/ab6c6f80-01bd-11e7-88dc-7fd1f191f622.jpg)

**Comment by bdew** [comment]
Derp! Should be fixed in next build.
