### ISSUE TITLE
[1.10.2] Question about custom bee (spawn mob eggs ?)

### ISSUE THREAD

**Issue by DV666** [bdew-minecraft/gendustry#219]
Hi bdew, i am testing to add somes bees on my modpack and i want to create a bee which product a particular mob egg but the question is... how ?

I try many things and i get crash or an empty mob egg because on 1.10.2, they don't use id anymore but NBT Tags now.... and i am lost !

It's possible to do that on yours config files or not ? :} 

Thanks in advance !

**Comment by bdew** [comment]
Currently you can't specify NBT tags. Maybe in the future (tho implementing all the syntax for that is going to be a pain in the arse...)
