### ISSUE TITLE
[gendustry/gendustry]: Created 52 BC triggers for Forestry error codes. Information search

### ISSUE THREAD

**Issue by jasonsaffle13** [bdew-minecraft/gendustry#221]
Server seems to be running fine. I have searched but found no information. I am running IC2C (industrial clasic) I think there is an API problem as well but I am aware of that and found info for it.

https://paste.ubuntu.com/24361298/

**Comment by bdew** [comment]
Sorry if i'm missing something, but what is the actual problem?

**Comment by bdew** [comment]
That message about error codes is normal, it means the game registered forestry error states (like no drone, no flowers, etc.) for BC logic gates.

**Comment by jasonsaffle13** [comment]
Just searching through log and wondered what this 52 bc thing was about. I
do not see any issues or problems but was looking for information about it.

**Comment by bdew** [comment]
Well see what i wrote above. It adds triggers you can use in BC gates to detect various error conditions.
