### ISSUE TITLE
[Enhancement] Prevent confusion from altering Queen's genes

### ISSUE THREAD

**Issue by mezz** [bdew-minecraft/gendustry#222]
A lot of new Gendustry players alter the genes of a queen because it seems like they're getting twice as much work done at once, but really what happens is only half the genome is changed. Then they breed the queens with automation and end up with pretty confusing results.
I think that either queen bee genomes should not be alterable, or Gendustry should alter both genomes for a higher cost, or some other solution like that.

**Comment by bdew** [comment]
Sorry kinda forgot about this... i've changed it now to not accept queens.

**Comment by mezz** [comment]
Thanks!
