### ISSUE TITLE
Forestry Obfuscation Problem

### ISSUE THREAD

**Issue by mezz** [bdew-minecraft/gendustry#223]
Binnie's mods in 1.11 has an obfuscation conflict with `IAllele.getName`.
I want to avoid this conflict in the future, so I added `IAllele.getAlleleName`.

Nothing is broken right now, but when Binnie's is released it will break when Gendustry is present as long as there are calls to `getName`.
Please switch to using this new method when you get a chance.
The minimum Forestry version for using this new method is 5.3.4.

**Comment by bdew** [comment]
Thanks for the heads up. I'm on a bit of a break from MC modding, but i'll try to get it updated soon.
