### ISSUE TITLE
Replicating Yellorite Bees

### ISSUE THREAD

**Issue by BGNDR** [bdew-minecraft/gendustry#224]
Im not sure if this is an issue or not but I thought to post it here. Im playing ftb beyond and have gotten my yellorite princess and drone. I want to make more drones and was wondering if there is an easy way to make them with out going through mutation process to get them. I have tried breeding them with winter bees to get there fertility up to produce more drones but it seems like fertility x1 is more dominate than fertility x4 which makes it really hard to mass produce yellorite queens. just wonderIng?

**Comment by ktole1999** [comment]
could use production upgrades on the apiary

**Comment by IMarvinTPA** [comment]
Just make a bunch of winter drones with 4x, get a gene sample of the 4x reproduction and put it on a template.  apply that template to your yellorite princess and drone and voila, lots of yellorite drones.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
