### ISSUE TITLE
[1.12] Creative Bug

### ISSUE THREAD

**Issue by TheLimePixel** [bdew-minecraft/gendustry#227]
Many mods have had this bug when porting to 1.12 and now yours is one of them. The bug is basically when the items from your mod show up on every creative tab, vanilla and modded. It's not something game-breaking, but it can be annoying for some:
 
![image](https://user-images.githubusercontent.com/25333164/28676171-42cd117a-72ea-11e7-942f-9485f1bd4eea.png)

Apparently the Production Upgrade has a broken texture as well.

**Comment by bdew** [comment]
Thanks for the report, fixed in latest build.
