### ISSUE TITLE
Bee and Upgrades disappearing from Industrial Apiary

### ISSUE THREAD

**Issue by Alrawn** [bdew-minecraft/gendustry#228]
Put (several) Batty Queens into an Industrial Apiary with Light, Lifespan (x4) and Seal Upgrade. As soon as the Queen starts working, the Apiaries UI closes and upon reopening, is totally empty (Bee gone, all Uprgades gone). I havent seen this behaviour with any other bee so far.

Versions used:
Minecraft 1.11.2
Forge-13.20.1.2386
forestry_1.11.2-5.3.4.135
gendustry-1.6.5.9-mc1.11.2
magicBees-beta-3.0.3

**Comment by bdew** [comment]
anything appearing in the client or server logs when it happens?

**Comment by Alrawn** [comment]
It's hard to see anything related, I'll try another and check the logs.

**Comment by Alrawn** [comment]
Found sth:
https://pastebin.com/42LwMWS9

**Comment by bdew** [comment]
Relevant part here:

    java.lang.NoClassDefFoundError: elec332/core/util/EntityHelper
    at elec332.core.compat.forestry.allele.AlleleEffectSpawnMob.spawn(AlleleEffectSpawnMob.java:109)
    at elec332.core.compat.forestry.allele.AlleleEffectSpawnMob.doEffectThrottled(AlleleEffectSpawnMob.java:98)
    at elec332.core.compat.forestry.allele.AlleleEffectThrottled.doEffect(AlleleEffectThrottled.java:45)
    at forestry.apiculture.genetics.Bee.doEffect(Bee.java:183)

The bee is trying to spawn something and that code is throwing an error. This is unrelated to gendustry and would happen just as well in a vanilla forestry apiary. 

The mod mentioned in the error is [ElecCore](https://github.com/Elecs-Mods/ElecCore), so you probably should report it there.
