### ISSUE TITLE
Custom Bee with Better Questing Crash

### ISSUE THREAD

**Issue by davqvist** [bdew-minecraft/gendustry#230]
MC 1.12.1
Forge 2485
Gendustry 1.6.5.4
(will update to 1.12.2 shortly)

I made custom bees, but when I select the custom bee in a Retrieval Task with Better Questing, the game crashes: https://pastebin.com/DfxVb7ni
Not sure if this is Gendustry's or BQ's fault.

Bee config: https://pastebin.com/0TAkRkmA

**Comment by bdew** [comment]
Hm, i'm not familliar with Better Questing, are you sure it's not messing up the NBT data when generating the reward?

Can you spawn the bee from JEI and see if it works?

**Comment by davqvist** [comment]
Yeah I have the bee in my inventory, spawned from JEI, but when I select it for a hand-in quest, the game crashes.

**Comment by bdew** [comment]
If it works correctly from JEI then the issue is not with Gendustry or the bee definition. Likely it's not stored/created correctly in the quest mod, causing invalid data in nbt which leads to the crash.
