### ISSUE TITLE
this recipe doesn't wanna remove when i use crafttweaker please advise?

### ISSUE THREAD

**Issue by trilexcom** [bdew-minecraft/gendustry#232]
hi bdew

hi gendustry community / bdew i have a interesting question for you, when i remove gendustry recipe like this script recipes.remove(<gendustry:power_module>);
recipes.addShaped(<gendustry:power_module>,
 [[<ore:gearBronze>, <ic2:plate:2>, <ore:gearBronze>],
  [<minecraft:piston>, <minecraft:redstone>, <minecraft:piston>],
  [<ore:gearBronze>, <forestry:royal_jelly>, <ore:gearBronze>]]); i still see the recipe for some reason plus my recipe for it 

attached is screenshot of recipe!

https://imgur.com/JBreQqy

Gendustry Version :  Gendustry 1.6.5.5 (MC 1.12.2)
MC : 1.12.2
CT version  : CraftTweaker2-1.12-4.0.8

attached is crash log : https://pastebin.com/eWSdjHt8

**Comment by bdew** [comment]
See my reply to #233, same issue.
