### ISSUE TITLE
[1.12.2] Genetic Templates can be pulled out of the Genetic Imprinter

### ISSUE THREAD

**Issue by Xiaminou** [bdew-minecraft/gendustry#239]
When using Item Eject Cover on the Genetic Imprinter it will also eject the Genetic Template.
Video for clarification: https://youtu.be/uHGv3nSC8go

Minecraft: 1.12.2
Forge: 2544
Mods: [list.txt](https://github.com/bdew/gendustry/files/1488919/list.txt)

**Comment by bdew** [comment]
This is intentional, the template can be removed from any side, but only when no imprinting is ongoing and the input slot is empty.
