### ISSUE TITLE
(1.6.4) Gendustry 1.1.2: Coloured combs/honey drops don't have configurable IDs

### ISSUE THREAD

**Issue by Geijoh** [bdew-minecraft/gendustry#24]
The title explains it pretty well!

**Comment by bdew** [comment]
Huh? They do.
In gendustry.cfg, in item section

```
I:HoneyComb=15006
I:HoneyDrop=15007
```

Those are the IDs fro all custom combs/drops

**Comment by Geijoh** [comment]
Apologies. This was an extreme derp on my part (I looked at the wrong version of the config (Various test profiles/versions)).
