### ISSUE TITLE
scooporator not chargeable

### ISSUE THREAD

**Issue by idealjo** [bdew-minecraft/gendustry#25]
scooporator not charging in ender io bank or AE2 charger.

**Comment by bdew** [comment]
Assuming this is in 1.7.2?

For now RF support is disabled in 1.7.2 builds and both of those use it's API for charging. I will be doing some work on 1.7.2 version soon and will look into re-enabling RF (apparently the energy API is now stable?)

At any rate for now you can use IC2 to charge it.

**Comment by idealjo** [comment]
yes in 1.7.2

the RF api is now stable
https://twitter.com/TeamCoFH/status/468536040131919872

thanks for the answer

**Comment by idealjo** [comment]
moreover, once charged via IC2 EU, the scooporator takes ages to break a hive. like diamond pick on obsidian

**Comment by bdew** [comment]
I've fixed the scoop to work correctly.

RF support is enabled now but it won't work unless some other mod bundles the API with the proper @API annotation... And nobody seems to do that for now.

This won't be an issue once TE is related but until then i don't have a solution.

**Comment by bdew** [comment]
I've opened a bug against enderio asking CP to include the @API declaration - CrazyPants/EnderIO#773

**Comment by tterrag1098** [comment]
I'll do this in my mod as well, thanks for the heads-up :)

**Comment by bdew** [comment]
Looks like latest builds of EnderIO work with 1.7.2 / 1.7.10 versions.
