### ISSUE TITLE
Using a bucket on the DNA Extractor removes liquid from the machine but does not fill the bucket

### ISSUE THREAD

**Issue by superfluke** [bdew-minecraft/gendustry#250]
Expected: Right clicking the DNA Extractor with a bucket should provide the player with a filled bucket of Liquid DNA

Actual: Using a bucket on the DNA Extractor deletes a bucket from the internal tank but does not return a filled bucket.

gendustry-1.6.5.6-mc1.12.2
bdlib-1.14.3.10-mc1.12.2
forge 1.12.2-14.23.1.2556

**Comment by bdew** [comment]
Should be fixed in next build, also improved handling of stacked fluid containers.
