### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by mrlamb** [bdew-minecraft/gendustry#253]
We've been getting an odd crash tonight that's referencing your mod as well as Thermal Expansion so I'm posting to both of you in hopes we can figure out what's going on. The crash seems to happen when breaking an industrial apiary. This apiary was connected to a leadstone fluxduct. It hasn't happened every time we've broken it until recently. By that I mean I broke one a few times in the last couple days and no crash, however another player broke two tonight and crashed both times. This latest crash affected all three who were logged into the server, but apparently the server continued on with no problem (expected, honestly as it appeared to be a rendering problem).

Modpack: Direwolf20 for 1.12.2 on the latest release version via twitch.
Crash log: https://pastebin.com/67azCyy8

I'll be happy to provide any more information you might need, just let me know.

**Comment by bdew** [comment]
Fixed, see the other bug.
