### ISSUE TITLE
[BUG] Territory Upgrades not expanding Bees effect range.

### ISSUE THREAD

**Issue by Veggetossj** [bdew-minecraft/gendustry#26]
Im playing on Monster 1.1.1 and was using Gendustry to get a Tropical Bee with the Exploring Effect and Maximum Range (15x15). Using the Territory Upgrades on the Industrial Apiary i was trying to increase this range, but they do not seem to work at all. As soon as I walked outside of the Bee's original range, it stopped giving me XP.

**Comment by bdew** [comment]
Looks like a problem in forestry, it ignores range modifiers for some (most?) effects. Can't fix this from my side.

https://github.com/ForestryMC/ForestryMC/blob/cfa8d5302557a512ac2d4e22ae647e232836b27c/forestry_common/apiculture/forestry/apiculture/genetics/AlleleEffectThrottled.java#L103
