### ISSUE TITLE
OreDict Errors

### ISSUE THREAD

**Issue by S60Team** [bdew-minecraft/gendustry#28]
Bee Receptacle is used in recipes as dye\* and dropHoney.
Mutagen Tank is used in recipes as beeComb.

Minecraft 1.6.4, Gendustry v1.1.3.78

**Comment by bdew** [comment]
Huh that's odd. Can you verify that you don't have item id conflicts and upload your full log?

**Comment by S60Team** [comment]
I have no ID conflicts...
But i'l try to change id's for items and answer as soon as i can.

**Comment by S60Team** [comment]
Fixed by changing id for gendustry items.
It because of updating Gendustry (version that add new honeycomb).
That's was odd...

Please close the issue.

PS: Any chance to disable those Colored Bees?

**Comment by bdew** [comment]
Create an empty file in config/gendustry/overrides/bees_color.cfg - that should prevent them from being loaded.
