### ISSUE TITLE
[ Bug ] Simple Wired Charger don't charge the Scooporator MX200 Turbo

### ISSUE THREAD

**Issue by HurtsAsHell** [bdew-minecraft/gendustry#290]
I have already opened an issue on the "[EnderIo](https://github.com/SleepyTrousers/EnderIO/issues/4987)" mod and they told me that the problem is not theirs.
 
I have not found other issues regarding this topic so, if they existed, could you link it?

else

How can I solve the problem?

_Minecraft Version_ : 1.12.2
_GenDustry Version_ : 1.6.5.8

**Comment by mecwerks** [comment]
Same issue here, even with the standard wired charger

**Comment by HurtsAsHell** [comment]
I believe the creator is dead
@mecwerks
