### ISSUE TITLE
[suggestion] mariculture support

### ISSUE THREAD

**Issue by Frontrider** [bdew-minecraft/gendustry#31]
Mariculture has a really similar system with fishes what you could build on too.

**Comment by bdew** [comment]
This is an interesting idea, but would require a lot of code to work properly with different APIs.

Maybe sometime in the future.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you belive it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
