### ISSUE TITLE
Reported crash (IC2 api?)

### ISSUE THREAD

**Issue by BevoLJ** [bdew-minecraft/gendustry#34]
Here is the report: https://github.com/BevoTechPack/BevoTechPack/issues/68

His crash:
http://pastebin.com/kiJTjS7D

" i had a centrifuge/squeezer/carpenter running off zombie generator with ender io cables then i had a mutagen producer/advanced mutatoron/industrial apiary runnin off a dimensional transciever with ender io cables"

The pack is using: 
bdlib-mc1710-1.4.0.3.jar
gendustry-mc1710-1.3.0.3.jar
enderio-2.0_beta.152.jar
industrialcraft-2-2.2.540-experimental.jar

**Comment by bdew** [comment]
Fixed in 1.3.0.5, available from [jenkins](http://jenkins.bdew.net/view/MC%201.7.10/)
Note that you will also need to update BdLib.

**Comment by BevoLJ** [comment]
You're the best.  Cheers.  :)
