### ISSUE TITLE
Industrial Apiary not Recognizing Correct biome factors.

### ISSUE THREAD

**Issue by cproo12** [bdew-minecraft/gendustry#35]
Using an Industrial Apiary with an Industrious bee in it in a River biome.

Apiaries work with the same exact bee, but not Industrial Apiaries.

**Comment by bdew** [comment]
What version of Gendustry and Forestry?

**Comment by cproo12** [comment]
Latest versions of both on 1.7.10

**Comment by bdew** [comment]
I tried and can't reproduce that. Do you have any mods that have anything to do with biomes? Is that in single player or on a server? Is the area chunk loaded in any way?

**Comment by cproo12** [comment]
The area is not chunkloaded, it was on a server.

We have Biomes O Plenty, Twilight Forest, Random Things, and Natura.

Those are ALL mods that add or modify biomes.

EDIT:  The river biome isn't natural, is most likely the problem. It was painted with the Random things biome painter. I still don't understand why it doesn't work though. Normal Apiaries work.

**Comment by bdew** [comment]
Please try this version: http://jenkins.bdew.net/job/gendustry-1.7.10/8/artifact/build/libs/gendustry-mc1710-1.3.0.8.jar

Still can't reproduce but I think the problem was that i was caching the biome when the apiary is created/loaded and it was getting the original biome before RT did it's thing.

**Comment by cproo12** [comment]
I'll try it out when I get home. Visiting family now, so I am busy. Will tell my friend to try it out though as he runs the server.

**Comment by bdew** [comment]
So can someone confirm/deny that the bug is fixed? I'll assume it's all good unless someone complains soon :P

**Comment by Mejari** [comment]
I'm seeing the same behavior (Except in a forest biome, not a river biome) using the Yogscast Complete Pack, MC 1.6.4, Forestry 2.3.1.1, Gendustry 1.1.3.

I understand a version that old likely isn't supported, but I thought I'd add another data point :)

**Comment by bdew** [comment]
Yeah the same problem probably exists in 1.6.4 versions, I assume this happens with something that modifies a biome as well?

I'll post a (hopefully) fixed build for 1.6.4 soon

**Comment by bdew** [comment]
For 1.6.4 please try this version: https://www.dropbox.com/s/q3nkhrckpem3rt0/gendustry-mc164-1.1.3.fix1.jar

**Comment by Mejari** [comment]
Wow, what a fast response! Dropped it in and it works perfectly, thank you!

**Comment by bdew** [comment]
The fix seem to work in 1.6.4 and the original reporter isn't responding, i'll assume this is fixed. If anyone still encounters this - comment here or submit a new report.
