### ISSUE TITLE
Crash when placing Gendustry Machines if IC2 is installed.

### ISSUE THREAD

**Issue by cproo12** [bdew-minecraft/gendustry#36]
Place it, and it corrupts the world. Only fix is removing gendustry.

I am guessing it has to do with EU power being accepted into the machines

http://pastebin.com/VFCDaV2F

**Comment by bdew** [comment]
Duplicate of #34 

Fixed in 1.3.0.5, available from [jenkins](http://jenkins.bdew.net/view/MC%201.7.10/)
Note that you will also need to update BdLib.
