### ISSUE TITLE
Crash with latest forestry (1.7.10)

### ISSUE THREAD

**Issue by BBoldt** [bdew-minecraft/gendustry#39]
- bdlib-mc1710-1.4.3.10.jar
- forestry_1.7.10-3.0.0.77.jar
- gendustry-mc1710-1.3.0.11.jar

http://pastebin.com/q9VJ1WPH

**Comment by ReillyBrogan** [comment]
Forestry build 69 is the last working build. Here is the changelog for 69 > 70 so you can see what changed: https://github.com/ForestryMC/ForestryMC/commit/83789ae8f726631aa435dcb6d445cbcc2b0c4e65
