### ISSUE TITLE
Client-Crash with Extrabees/NEI in 1.7.10

### ISSUE THREAD

**Issue by Keridos** [bdew-minecraft/gendustry#40]
http://paste.ee/p/mi3nW
gendustry-mc1710-1.3.1.12
NotEnoughItems-1.7.10-1.0.2.15
binnie-mods-2.0-dev2

Do not know what exactly caused it but it was a combination of these 3 mods.

If you can fix it, please do it ;-)
Thanks for making gendustry btw, its awesome :D

**Comment by bdew** [comment]
[Update NEI Addons](http://bdew.net/2014/08/21/nei-addons-1-12-1-for-minecraft-1-7-10/).

**Comment by Keridos** [comment]
Thanks!
