### ISSUE TITLE
Support Big Reactors ores as mutagen source in default config

### ISSUE THREAD

**Issue by XanderHess** [bdew-minecraft/gendustry#47]
Since Big Reactors' yellorium pretty much fills the same role as IC2's uranium in terms of being somewhat radioactive material to fuel reactors, I think it's reasonable to allow it to be used as mutagen source.

As a default value I'd suggest 2500mb.

Reasoning behind that is that you get 4 tiny piles of uran 235 and 10 uran 238 from fully processing 1 uranium ore, which is worth 9000mb.

Yellorium ore seems to be roughly twice as common and can be processed into 2 ingots so it should be worth 25% of that which would be 2250mb rounded up to 2500mb.

**Comment by bdew** [comment]
I'll add it in the next update.

**Comment by bdew** [comment]
I think it's more common than that 2.5 buckets feels like too much... I think i'll put it at 1 by default (can be changed in config)
