### ISSUE TITLE
Gendustry Extra Trees

### ISSUE THREAD

**Issue by Keridos** [bdew-minecraft/gendustry#55]
The industrial apiary currently does not seem to be working on extra trees trees.
Tested with binnies mods 2.0dev4 and gendustry 1.3.3.25.

**Comment by bdew** [comment]
Umm.. The apiary is for bees, not trees? :P

**Comment by Keridos** [comment]
There is a bee in there, a sieve upgrade and it does only produce vanilla oak pollen. After removing all the oaks in the vicinity it just stopped producing pollen although it had several extratrees trees near it.

**Comment by bdew** [comment]
I'll look into it when i have the time, tho the problem is probably between forestry and extra trees.

What version of forestry is this on? Also can you verify if you get pollen with a forestry alverary (with a sieve)?

**Comment by Keridos** [comment]
tested with forestry 3.0.0.170, but also had it with a previous version ( a few weeks old)
even with newer forestry and gendustry and binnies mod versions it still does not work.

**Comment by Keridos** [comment]
I have been testing around in a dev environment a bit and I noticed that it seems as if onPollenRetrieved is never called for the extraTrees trees. So it seems that gendustry is not the cause of this. When I find a workaround I might put up a pull request for it.

**Comment by bdew** [comment]
Sorry i've been somewhat busy and had no time to really take a look at this.

If it's indeed not called then it's definitely something between ET and Forestry

**Comment by Keridos** [comment]
This is still present with the newest releases including binnies mods. Binnie stated that it should be working, as he needed to significantly increase the chance of pollen drops and it should work with his alceary sieves as well. Did not manage to get Gendustry sieves working on my server however.

**Comment by bdew** [comment]
Sorry about letting this kinda fall off my radar.

I've just tested with binnie mods pre6b, forestry 3.4.0 and latest gendustry and i had no problem getting pollen from binnie's trees.

Are you still having problems with this?

**Comment by Keridos** [comment]
Oh, totally forgot about this issue, sorry. Some update with binnies mods fixed this. Could have been your mod as well, but I strongly suspect binnies mods to have been the cause of this. Works fine for me in the newer releases as well.
