### ISSUE TITLE
[suggestion] Texture Alterations

### ISSUE THREAD

**Issue by CyanideX** [bdew-minecraft/gendustry#57]
Changing the cover textures to an overlay instead of replacing the block face texture would allow for easier retexturing with resource packs. :)

![minecraft_1 7 10_2014-07-22_10-59-20](https://cloud.githubusercontent.com/assets/3106700/4446132/c3904fc0-47ff-11e4-9825-2a0caccdf72a.png)

**Comment by bdew** [comment]
Hm, makes sense, i'll do this when i have the time

**Comment by bdew** [comment]
Will be in next release. Note that partial transparency is not supported. Also, I will not change the default textures, if you want a texture with transparent parts you will need to provide one in your texture pack.
