### ISSUE TITLE
industrial grafter doesn't work

### ISSUE THREAD

**Issue by BakermanLP** [bdew-minecraft/gendustry#59]
Hello,

in the latest gendustry version ( gendustry-mc1710-1.4.0.35.jar ) the industrial grafter doesn't work. forestry_1.7.10-3.1.1.244-unstable.jar is the counterpart and many other mods. There also doesn't seem to be a error message in the logs.

If you need additional informations about configs or used mod versions just have a look at:
https://github.com/BakermanLP/ModpackProjectRETv7

Michael (aka BakermanLP)

**Comment by bdew** [comment]
Ugh i'll look at it, i guess something got changed in the API again

**Comment by Unrepentant-Atheist** [comment]
Yo dawg @BakermanLP where the bleeding edge jenkin builds for Forestry at?

**Comment by bdew** [comment]
http://ic2api.player.to:8080/job/Forestry_Dev/
