### ISSUE TITLE
Crash when moving from pre-initialization to initialization

### ISSUE THREAD

**Issue by bengalgod** [bdew-minecraft/gendustry#63]
http://paste.atlauncher.com/view/6fc6ec3d

I'm using 1.7.10 and a fistful of mods that are stable until I add gendustry, at which point gendustry errors out.  Near as I can tell I have the required stuff in place, so I'm not exactly sure what's happening.

Forge version is 10.13.1.1229
Forestry version is 3.1.1.4

**Comment by bdew** [comment]
Gendustry 1.4.1 is not compatible with BuildCraft 6.0.x.
Either upgrade to BC 6.1 or downgrade to Gendustry 1.4.0

**Comment by bdew** [comment]
Also please don't post logs from 39 different sessions when only one of them has the relevant error, looking through that was painful.

**Comment by bengalgod** [comment]
Thank you very much for your swift response, I really appreciate it.
I'm sorry about the log thing, I just clicked on the "upload log" button and assumed (wrongly) that it would only do the last session.
