### ISSUE TITLE
Updating Gendustry to 1.4.1.43 Causes Crash

### ISSUE THREAD

**Issue by SamRaven2** [bdew-minecraft/gendustry#64]
I understand this may be a compatibility issue with another mod in my pack, however I am unable to determine what it is myself and updating Gendustry to version 1.4.1.43 is what causes the game to crash. Leaving Gendustry at version 1.4.0.41 lets the pack launch properly.

The crash happens before reaching the Mojang screen if this is helpful information.

A crash log can be found here: [CrashLog](http://paste.ee/p/WwDi8)

**Comment by bdew** [comment]
The only mod mentioned in the callstack is Journey Map

```
at net.techbrew.journeymap.forgehandler.ChatEventHandler.invoke(ChatEventHandler.java:36)
```

Nothing to do with Gendustry.

**Comment by bdew** [comment]
The log you posted is with gendustry 1.3.4.29 - maybe wrong log? :P

**Comment by SamRaven2** [comment]
You are correct, that was the wrong log...meaning I've been looking at the wrong log the entire time. For some reason MultiMC decided to show the oldest crash log as opposed to the latest one. If I can't determine the issue now I will open a new issue with the proper crash log if that is acceptable to you?

**Comment by bdew** [comment]
sure
