### ISSUE TITLE
Updating Gendustry Causes Crash - Correct Log

### ISSUE THREAD

**Issue by SamRaven2** [bdew-minecraft/gendustry#65]
Sorry about the earlier post, It was from a much earlier crash that actually did have to do with Journeymap (hehe, derp on my part)

Here is the correct crash log for the crash I am getting, which does appear to be Gendustry related.

[CrashLog](https://gist.github.com/SamRaven2/3781619ca204823686ec)

**Comment by bdew** [comment]
Hmm that's odd, it crashes because of an old version of BuildCraft API in one of the other mods, though you don't have BC itself installed. I'll look into making this check more reasonable.

**Comment by bdew** [comment]
Actually try updating Forestry to a newer unstable version, i think this will fix the crash 

http://ic2api.player.to:8080/job/Forestry_Dev/

**Comment by SamRaven2** [comment]
Yes, updating Forestry seems to have fixed it. Seems like a bit of an odd fix though. I'm assuming Forestry is the mod using the old API.

**Comment by bdew** [comment]
This whole BC 6.0 -> 6.1 transition is odd :P

Gendustry requires Forestry to run, and Forestry always bundles BC API, so my code kind'a assumes it's there without really checking.

The point is you need something to provide the new API, and either updating forestry or installing BC itself is the easiest way. You might still have something with the old API as well and but it shouldn't (i hope) cause issues.
