### ISSUE TITLE
Crash with Gendustry 1.4.1.43

### ISSUE THREAD

**Issue by Nhawks1717** [bdew-minecraft/gendustry#67]
I'm getting a crash with a custom mod pack only when I have Gendustry enabled. And yes I went through the closed issues and saw there were some problems with people not having the version of Forestry with the Buildcraft API, I do have that version. Here is the crash report that is generated when launching.

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 11/10/14 9:40 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/bdew/gendustry/compat/triggers/TriggerProvider$
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/bdew/gendustry/compat/triggers/TriggerProvider$
    at net.bdew.gendustry.Gendustry$.preInit(Gendustry.scala:65)
    at net.bdew.gendustry.Gendustry.preInit(Gendustry.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: net.bdew.gendustry.compat.triggers.TriggerProvider$
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 38 more
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/statements/ITriggerProvider
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 40 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.statements.ITriggerProvider
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 44 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 168711928 bytes (160 MB) / 647368704 bytes (617 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:PermSize=256m -XX:MaxPermSize=512m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 111 mods loaded, 111 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1236} [Forge Mod Loader](forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1236} [Minecraft Forge](forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.67} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.67-universal.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    debug{1.0} [debug](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized
    bdlib{1.5.1.32} [BD Lib](bdlib-mc1710-1.5.1.32.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.9.0} [BiblioCraft](BiblioCraft[v1.9.0][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.0B8} [CoFH Core](CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized
    Forestry{3.1.1.4} [Forestry for Minecraft](forestry_1.7.10-3.1.1.4.jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized
    ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized
    BigReactors{0.4.0rc11} [Big Reactors](BigReactors-0.4.0rc11.jar) Unloaded->Constructed->Pre-initialized
    BinnieCore{2.0-dev5} [Binnie Core](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    Botany{2.0-dev5} [Botany](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    ExtraBees{2.0-dev5} [Extra Bees](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    ExtraTrees{2.0-dev5} [Extra Trees](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    Genetics{2.0-dev5} [Genetics](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{3.3.1} [Carpenter's Blocks](Carpenter's Blocks v3.3.1 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
    Cogs{0.1.4pre1} [Cogs of the machine](cogs-1.7.10-0.1.4pre1.jar) Unloaded->Constructed->Pre-initialized
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded{1.7.10R2.8.0RC4} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized
    Railcraft{9.3.3.0} [Railcraft](Railcraft_1.7.10-9.3.3.0.jar) Unloaded->Constructed->Pre-initialized
    EnderIO{1.7.10-2.1.8.260} [Ender IO](EnderIO-1.7.10-2.1.8.260.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.5.25} [EnderStorage](EnderStorage-1.7.10-1.4.5.25-universal.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    extracells{2.1.12} [ExtraCells](ExtraCells-1.7.10-2.1.12bnull.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.314} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-161.jar) Unloaded->Constructed->Pre-initialized
    MagicBees{1.7.10-2.1.22} [Magic Bees](magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized
    gendustry{1.4.1.43} [GenDustry](gendustry-mc1710-1.4.1.43.jar) Unloaded->Constructed->Errored
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded->Constructed->Pre-initialized
    Mekanism{7.1.0} [Mekanism](Mekanism-1.7.10-7.1.0.92.jar) Unloaded->Constructed->Pre-initialized
    MekanismGenerators{7.1.0} [MekanismGenerators](MekanismGenerators-1.7.10-7.1.0.92.jar) Unloaded->Constructed->Pre-initialized
    MekanismTools{7.1.0} [MekanismTools](MekanismTools-1.7.10-7.1.0.92.jar) Unloaded->Constructed->Pre-initialized
    minechem{5.0.5.302} [Minechem](Minechem-1.7.10-5.0.5.302.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC4} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC3} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC4} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC4} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC3} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC3} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC4} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC3} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MrTJPCoreMod{1.0} [MrTJPCoreMod](MrTJPCore-1.7.10-1.0.2.4-universal.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Core{4.5.3.54} [ProjectRed](ProjectRed-1.7.10-4.5.3.54-Base.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Exploration{4.5.3.54} [ProjectRed-Exploration](ProjectRed-1.7.10-4.5.3.54-World.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC3} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC3} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC3} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC4} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC4} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC4} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC4-676.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.3.11} [NEI Addons](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    neiintegration{1.0.0} [NEI Integration](NEIIntegration-MC1.7.10-1.0.0.jar) Unloaded->Constructed->Pre-initialized
    ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-223.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-430.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Transmission{4.5.3.54} [ProjectRed-Transmission](ProjectRed-1.7.10-4.5.3.54-Integration.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.7.10-1.3.6.69-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers{1.3.6.69} [OpenComputers](OpenComputers-MC1.7.10-1.3.6.69-universal.jar) Unloaded->Constructed->Pre-initialized
    MapWriter{2.1.1} [MapWriter](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Opis{1.2.3} [Opis](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    harvestcraft{1.7.10b} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10c.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Transportation{4.5.3.54} [ProjectRed-Transportation](ProjectRed-1.7.10-4.5.3.54-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Compatibility{4.5.3.54} [ProjectRed-Compatibility](ProjectRed-1.7.10-4.5.3.54-Compat.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Integration{4.5.3.54} [ProjectRed-Integration](ProjectRed-1.7.10-4.5.3.54-Integration.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Illumination{4.5.3.54} [ProjectRed-Illumination](ProjectRed-1.7.10-4.5.3.54-Lighting.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Expansion{4.5.3.54} [ProjectRed-Expansion](ProjectRed-1.7.10-4.5.3.54-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
    simplyjetpacks{1.2.0} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized
    ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded->Constructed->Pre-initialized
    thaumcraftneiplugin{1.7.10-1.6a} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.6a.jar) Unloaded->Constructed->Pre-initialized
    thaumicenergistics{0.7.3b} [Thaumic Energistics](thaumicenergistics-0.7.3b.jar) Unloaded->Constructed->Pre-initialized
    TMechworks{1.7.10-67.34d1d9b} [Tinkers' Mechworks](TMechworks_mc1.7.10_0.2.8.jar) Unloaded->Constructed->Pre-initialized
    Translocator{1.1.1.13} [Translocator](Translocator-1.7.10-1.1.1.13-universal.jar) Unloaded->Constructed->Pre-initialized
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    denseores{1.0} [Dense Ores](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.314} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.

**Comment by bdew** [comment]
You don't. Either update to [forestry unstable](http://ic2api.player.to:8080/job/Forestry_Dev/), install BuildCraft or downgrade to Gendustry 1.4.0

**Comment by Nhawks1717** [comment]
Oh ok, when you said unstable I thought you meant this (http://prntscr.com/556lqs) unstable. I apologize :P

**Comment by Nhawks1717** [comment]
Wait..... totally read the information on that page wrong.... _facepalm_ I get it, nevermind, carry on! :P
