### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class net.bdew.gendustry.machines.apiary.ErrorCodes$

### ISSUE THREAD

**Issue by iarspider** [bdew-minecraft/gendustry#69]
Full log: http://pastebin.com/jx4RFixS

Gendustry 1.4.2.46
bdlib 1.5.1.32
BC 6.2.6
Forestry 3.1.1.328-unstable
WAILA 1.5.6a

**Comment by Tsunayoshi** [comment]
You could try this version of Gendustry: http://jenkins.bdew.net/job/gendustry-1.7.10-fu/
It is for the Forestry unstable version till 3.1.1.331

**Comment by bdew** [comment]
For unstable versions 283 to 331 use gendustry-fu 1.4.2.3
For versions 332 and above use   gendustry-fu 1.4.3.5

**Comment by iarspider** [comment]
Thanks, that fixed it.
