### ISSUE TITLE
Mutations obtained via Mutatron are not registered in Apiarist's Database (from BinnieCore/ExtraBees)

### ISSUE THREAD

**Issue by iarspider** [bdew-minecraft/gendustry#7]
Mutations obtained via (advanced) Mutatron are not registered in Apiarist's Database (from BinnieCore/ExtraBees). The species are registered properly, but the mutations aren't.

**Comment by bdew** [comment]
I'll look into it tho i'm not sure if it's fixable, as the mutatron bypasses most of the mutation code in forestry (including breeding tracking).
