### ISSUE TITLE
issue with the newst unstable forestry version

### ISSUE THREAD

**Issue by Tsunayoshi** [bdew-minecraft/gendustry#70]
Hey,

I have seen you have made a special gendustry version for unstable forestry. The latest fu version let's the game crash again. Maybe you could be so kind and make an updated gendustry-fu version again?

Here's the crashlog:
http://pastebin.com/nvwiuth9

forestry_1.7.10-3.3.0.334-unstable.jar
gendustry-fu-mc1710-1.4.2.3.jar
bdlib-mc1710-1.5.1.32.jar

I have tried the last unstable versions. After version 331 there is a problem. According to the changelog, it should be one of this:
#332 (15.12.2014 16:46:23)

```
Fixes #369 The Solding Iron and other Cicruit stuff should no longer crash if no layouts are defined. (commit: ccdcce47cc77eb24102234c55d6d52ec7df89d50) — CovertJaguar / githubweb
Bump version (commit: d4b8c6b5032d1c813f265a5b6797493a25e3c915) — CovertJaguar / githubweb
For whatever reason the Potion.isBadEffect() reflection was giving me generics related compile errors. This fixes it. (commit: aaa00d01842b7c9be16f7c53d7dccb88cf7d2d8b) — CovertJaguar / githubweb
```

**Comment by bdew** [comment]
Try the latest build from http://jenkins.bdew.net/job/gendustry-1.7.10-fu

**Comment by Tsunayoshi** [comment]
THAT was impressive quick! It seems to work now for client- and serverside. Thanks a lot!

**Comment by bdew** [comment]
Yay!
