### ISSUE TITLE
Error: forestry.api.core.ErrorStateRegistry.getErrorStateFromCode(S)Lforestry/api/core/IErrorState;

### ISSUE THREAD

**Issue by Protheus** [bdew-minecraft/gendustry#71]
Error: cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: forestry.api.core.ErrorStateRegistry.getErrorStateFromCode(S)Lforestry/api/core/IErrorState;

http://pastebin.com/fG7qzyGp

Forestry: 3.3.0.337-Unstable
GenD: 1.4.3.5 (FU)
Forge: 1264

**Comment by Protheus** [comment]
Updated both gendustry (1.4.3.6) and forestry (3.3.0.341) to latest and issue is then solved

**Comment by bdew** [comment]
yeah builds >=337 need gendustry-fu 1.4.3.6 due to api changes
