### ISSUE TITLE
Get a Crah with lastest Forestry Unstable Verion 342 and Gendustry 1.4.3.47

### ISSUE THREAD

**Issue by Dream-Master** [bdew-minecraft/gendustry#72]
https://gist.github.com/Dream-Master/670ec0be76ea30bdf8ca#file-gistfile1-txt

i post it at Forestry Github too.

https://github.com/ForestryMC/ForestryMC/issues/381

**Comment by bdew** [comment]
Forestry unstable is not compatible with stable releases of Gendustry due to API changes. Grab a matching version from [here](http://jenkins.bdew.net/job/gendustry-1.7.10-fu/)

**Comment by Dream-Master** [comment]
Thanks i will test it.
