### ISSUE TITLE
[Crash]: Crash when trying to enter the GUI of a Powered Industrial Apiary!

### ISSUE THREAD

**Issue by Lanse505** [bdew-minecraft/gendustry#74]
Crash Log: http://pastebin.com/U6BzN5GC

Crash Reason: Power a Industrial Apiary > Open Industrial Apiary GUI = Crash

Mod Versions: 
GENDUSTRY-MC1710-1.4.2.46
BDLIB-MC1710-1.5.1.32

**Comment by bdew** [comment]
Update to [gendustry 1.4.3](http://bdew.net/gendustry/), earlier versions don't support forestry 3.3.0
