### ISSUE TITLE
NEI Breaks in 1.4.4.50

### ISSUE THREAD

**Issue by ShawnRHayes** [bdew-minecraft/gendustry#76]
no crash but f7 and f9 work with nei but when hitting "e" there is no search or items displayed    NEI 1.0.3.74

**Comment by bdew** [comment]
yeah, it's the same bug with BinnieMods as #75, working on an additional fix

**Comment by ShawnRHayes** [comment]
thanks

**Comment by bdew** [comment]
try this http://jenkins.bdew.net/job/gendustry-1.7.10/51/artifact/build/libs/gendustry-mc1710-1.4.4.51.jar

**Comment by ShawnRHayes** [comment]
Good to go bdew, thank you so much !
