### ISSUE TITLE
Crash when looking up Liquid DNA

### ISSUE THREAD

**Issue by JasonMcRay** [bdew-minecraft/gendustry#77]
When you press R on the Liquid DNA from Gendustry, there is a crash. Only happens when Binnie Mods are also installed.

Crash log: http://pastebin.com/s4vQhHg1

Versions of mods included in the crashlog
Forge: 10.13.2.1323
Gendustry: 1.4.4.51
NEI: 1.0.4.83
Binnie mods: 2.0-pre4
CodeChickenCore: 1.0.4.35
Forestry: 3.3.0.6
bdlib: 1.6.0.36

Gendustry issue? or Binnie Mods? Just in case also reported to Binnie: https://bitbucket.org/binnie567/binnie-mods/issue/142/crash-when-looking-up-liquid-dna

**Comment by bdew** [comment]
Try this build http://jenkins.bdew.net/job/gendustry-1.7.10/lastSuccessfulBuild/artifact/build/libs/gendustry-mc1710-1.4.4.52.jar

**Comment by JasonMcRay** [comment]
Crash is no longer happening. Thanks for fast fix
