### ISSUE TITLE
Add industrial centrifuge

### ISSUE THREAD

**Issue by Karmacopper** [bdew-minecraft/gendustry#78]
I'd love to see an industrial centrifuge. In it's non-upgraded state would work identically to the vanilla Forestry version. Upgrades could improve power efficiency, production chance and speed of operation. Speed and power efficiency should probably be mutually exclusive or share the maximum allowed figure.

**Comment by Keridos** [comment]
Yes, a faster centrifuge would be awesome.

**Comment by Manuepolis23** [comment]
please add one.

**Comment by grydian** [comment]
I would also like to add my 2 cents and say please please this would be awesome!  :)

**Comment by Michal-MK** [comment]
Keeping the dream alive! when you have 10+ industrial apiaries with speed upgrades you need quite a lot of Centrifuges.

**Comment by grydian** [comment]
Having less machines would reduce lag...  A faster centrifuge would do just that...  Just a thought.

**Comment by Protheus** [comment]
:+1:

**Comment by mezz** [comment]
Centrifuges accept speed upgrade circuit boards in Forestry 4, allowing them to process up to twice as quickly. Maybe Gendustry could add more upgrade circuits.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
