### ISSUE TITLE
Suggestion[Additional tool]

### ISSUE THREAD

**Issue by Karmacopper** [bdew-minecraft/gendustry#79]
Industrial Pollen Collector. Low chance to collect a pollen sample from a leaf block, which is destroyed in the process. Recipe could include a pristine queen or some such. :D

**Comment by bdew** [comment]
Err... did you see the pollen collection kit i added in the last version? Haven't gotten around documenting it on the website but it's a single-use item that collects pollen from leafs.

**Comment by Karmacopper** [comment]
OO, no I didn't, Looking now :D

**Comment by Karmacopper** [comment]
Splendid, I might suggest silk rather than string, seems pretty cheap recipe :D

**Comment by bdew** [comment]
Well one of the reasons for adding it is to give users an option to breed trees if they don't want to get into bees or the bees module is outright disabled in forestry, so i don't want to make it depend on anything exclusive to bees.
