### ISSUE TITLE
[Enhancement] Add method to duplicate samples

### ISSUE THREAD

**Issue by ReillyBrogan** [bdew-minecraft/gendustry#8]
Can you please add a method to duplicate samples? I enjoy keeping an extra utils filing cabinet filled with at least one of every gene sample I get and using a species sample means creating a template and then sampling the bees created from it to get a replacement sample. Could you add a recipe where you craft a blank sample with a filled sample to get a second sample or add a sample duplicating machine?

**Comment by bdew** [comment]
I don't want to do this with a simple recipe, maybe a machine. Need to think about it.

**Comment by bdew** [comment]
Genetic Tranposer added in 4457c08e754f27960e5367ad03479985525261ad, allows duplicating samples and templates.
