### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Player3324** [bdew-minecraft/gendustry#81]
I've noticed that Gendustry 1.4.4.54 logs huge amounts of information to LogLevel INFO or higher during startup, swamping the console with uninteresting information and hiding what's actually relevant.

bdlib/gendustry logs 964 lines worth and gendustry/gendustry 265 lines.

It'd be nice if extraneous logging could be removed or at least moved to DEBUG or TRACE.

**Comment by bdew** [comment]
I'll move most of the spam to DEBUG.

Don't want to remove them because of how configurable my mods are (and most of the spam is from loading configuration) and I want to see what the user actually changed without having to chase after them to upload configs, etc.
