### ISSUE TITLE
Issues with pollen collector kit and Botany Flowers

### ISSUE THREAD

**Issue by Karmacopper** [bdew-minecraft/gendustry#82]
Attempting to collect pollen from Botany flowers: Computer says no!

http://paste.ee/p/QOTTB

**Comment by bdew** [comment]
Oh heh... wasn't even aware they implemented IPolinateable.

**Comment by Karmacopper** [comment]
Well they do liberate pollen with sieve upgrade

**Comment by bdew** [comment]
Yeah i'll look into properly supporting them

**Comment by Karmacopper** [comment]
Cheers mate :D

**Comment by Karmacopper** [comment]
Further info, after changing the clear invalid allelle config option in forestry config, ended up with this little beauty:
![2015-02-18_23 16 03](https://cloud.githubusercontent.com/assets/7628623/6258854/25e96c54-b7c4-11e4-9946-50100256d447.png)

**Comment by bdew** [comment]
> G: 7048739x7048739

Ah, now i have my own version of the sacred tree :D

**Comment by bdew** [comment]
Try with this version: http://jenkins.bdew.net/job/gendustry-1.7.10/60/artifact/build/libs/gendustry-mc1710-1.4.6.60.jar

**Comment by Karmacopper** [comment]
Will try this version tonight when I get home from work and report back to you.

**Comment by Karmacopper** [comment]
Seems to work, had to snag the jenkins bdlib too
