### ISSUE TITLE
Issue with IguanaTweaksTConstruct

### ISSUE THREAD

**Issue by crunkazcanbe** [bdew-minecraft/gendustry#83]
I am seeing this in the console

[16:34:56] [Client thread/ERROR] [IguanaTweaksTConstruct]: Could not set harvestlevel of item.gendustry.scoop. Contact the Mod Author to properly support Item.setHarvestLevel().

Thank You!

-Crunk

**Comment by bdew** [comment]
Why does it have any business messing with my harvest levels?

**Comment by crunkazcanbe** [comment]
IDK Have you ever played with that mod ? Makes TConstruct harder , and more interesting , but like you said why would it want anything with your mod its not TConstruct . IDK ! Just thought I would point this out . Sorry if I bothered you . :)

**Comment by bdew** [comment]
Yeah i know the mod, just have no idea why it wants to change the mining level on my tools (i don't even think it affects anything).

I'll look into adding whatever is needed to stop that warning when i have the time.

**Comment by crunkazcanbe** [comment]
OK man thank you very much . Hope you have a good day !
- Crunk
