### ISSUE TITLE
Item/Block names with periods not supported

### ISSUE THREAD

**Issue by ChatFawkes** [bdew-minecraft/gendustry#84]
Hello,

When trying to edit the recipes for the Mutatrons I can't seem to use `GalacticraftMars:item.null@3` as a valid recipe item because it can't seem to parse periods.

Here is the related [crash report](https://gist.github.com/ChatFawkes/82e78913064330ce453f).

Using Gendustry version: 1.4.7.64 (BdLib version: 1.6.4.49)

**Comment by bdew** [comment]
Quote them, as in:

`GalacticraftMars:"item.null"@3`
