### ISSUE TITLE
Crash with Railcraft smoker

### ISSUE THREAD

**Issue by ultrasn0w** [bdew-minecraft/gendustry#86]
I updated my forge version from 1263 to 1291 and now I get this crah when I try to load my world:
http://pastebin.com/pNcqR4ue
Would be happy if this could be fixed :)

Greetings
ultrasn0w

**Comment by ultrasn0w** [comment]
Don't worry, something with the world was just fucked up.
https://i.imgur.com/dd95AjG.jpg

**Comment by bdew** [comment]
Probably something messed up when you updated and your FML block id map got regenerated.

The error is just a mismatch between the tile entity (RC smoker) and block (Gendustry transposer) and not a bug in either mod.

If you have a log from the first run after the update it might have errors that caused the corruption, but at this point your world is probably FUBAR unless you had backups.
