### ISSUE TITLE
Add support for IC2 crops

### ISSUE THREAD

**Issue by GotchaGimmeThanks** [bdew-minecraft/gendustry#89]
IC2 crops could certainly benefit from Gendustry. I'm not sure of a balanced way to use the mutatron on them, but certainly gene sampling and templates. It would be especially awesome to use the replicator to make many seedbags after achieving a good breed. Your thoughts?

**Comment by bdew** [comment]
Gendustry, for now, is based on Forestry API for all things Genetics, and can't work with other systems without major rewrites.

This could be interesting but for now it's in that "maybe one day when i have nothing more important to do" category, together with Mariculture fish and other similar ideas.

**Comment by GotchaGimmeThanks** [comment]
Ok, thanks. Love your work bdew.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
