### ISSUE TITLE
Servercrash with new unstable forestry

### ISSUE THREAD

**Issue by Tsunayoshi** [bdew-minecraft/gendustry#92]
Heyho!

I am getting a servercrash with forestry unstable 554 (updated from 541).

http://pastebin.com/iKG03PgK

forge 1401

**Comment by bdew** [comment]
Yay more API breakage. Update incoming

**Comment by bdew** [comment]
Should work with this version: http://jenkins.bdew.net/job/gendustry-1.7.10-fu/26/

**Comment by Tsunayoshi** [comment]
Thank you a lot. This looks good ;)
