### ISSUE TITLE
Mutatron (or Advanced Mutatron) not accepting breeding pairs

### ISSUE THREAD

**Issue by Lodran** [bdew-minecraft/gendustry#95]
I'm having trouble with the Mutatron, and honestly I'm not sure whether or not I just don't understand how it's supposed to work.

I've made a breeding pair (Resilient Princess + Imperial Drone) by altering only the species gene of a pair of Rocky Hive bees.

I can drop either the Princess or the Drone into the Mutatron, but it won't accept both at the same time.

The Mutatron is fully powered, and has a full tank of Mutagen.

**Comment by bdew** [comment]
Are you sure that is a valid mutation? does NEI show it?

Also what versions of all mods involved? (forestry, gendustry, binnie's)

**Comment by Lodran** [comment]
Resilient + Imperial is intended to produce a Lustrous bee.

The mods are all from Infinity 1.7 1.4.1.  According to https://feedthebeast.atlassian.net/wiki/display/PML/Infinity+1.7+1.4.1 , the versions are:

Forestry        3.5.3.11
Gendustry   1.4.9.76
Binnie's Mods   2.0-pre8

For what it's worth, I've also had trouble getting some of the items from Binnie's Mods to show recipes in NEI, which may be a related issue.

**Comment by Lodran** [comment]
Seems we also have:

Magic Bees  2.1.31

**Comment by bdew** [comment]
You have NEI Addons so this should be easy to see. Search NEI for resilent bee, press U on it and browse the mutation recipes. If it doesn't show up in there then it's a bug in whatever mod should provide it (i guess binnie's?) or in whatever documentation that says it should be there.

If it does exist in NEI i'll need to check why the mutatron isn't picking it up tomorrow when i'm at a proper PC.

**Comment by Lodran** [comment]
What we don't have is the Extra Bees mod, which is where the Lustrous bee is implemented.

I'm closing this for now, until I see another combination that's supposed to work and doesn't.

I suspect that NEI's database gets messed up from time to time, and when it won't show a recipe for something, things break.

**Comment by bdew** [comment]
There is no "NEI Database", atleast for mutations - my mods grab this data in real time from the actual mutation list in forestry API. 

If it doesn't show up in NEI it's most likely not registered with forestry and will not work.

**Comment by Lodran** [comment]
the reason I say that things seem to get messed up is that one of the things I tried when having trouble with the mutatron was to reproduce a bee I had already made (The Stannum bee, I think) and found that the parent bees would not be accepted.  Now that the server's been restarted, I'll give it another try.
