### ISSUE TITLE
[suggestion] Search field for mutatron recipes

### ISSUE THREAD

**Issue by Lodran** [bdew-minecraft/gendustry#96]
Currently, finding a specific bee amongst the mutatron recipies is particularly painful for two reasons:

1) You have to hover the mouse over each queen in order to see it's name.

2) There are over 200 pages of recipes to sort through.

I'd love to see a search feature which narrows down the field by species name, comb name, or (ideally) the products of centrifuged combs.

**Comment by bdew** [comment]
Adding a search field in NEI is not really feasible (atleast i don't know how to do that without all kinds of hackery in NEI internals).

If you have NEI Addons you can search by comb by pressing R on it and it will show what bee produces them, then press R on the bee to see mutations that produce it. Also the mutation display in NEI Addons shows the names on screen so it might be easier to use than mutatron NEI handler.

Alternatively you can press U on a bee to see what it produces and what mutations it can be in.

With NEI Integration you should be able to do that with centrifuge products too and "walk" up the chain.
