### ISSUE TITLE
Industrial Apiary crashes on certain bee cycles.

### ISSUE THREAD

**Issue by Armigus** [bdew-minecraft/gendustry#97]
I typically use automation and sieve upgrades on my apiaries.  Since I use underground warrens I set my bees' flower to mushroom and have the mushrooms on mycelium.  When the cycle completes the game crashes.  It's happened with Cuprum, Stannum, Ardite, and Industrious bees.

What's going on?

**Comment by bdew** [comment]
logs or it didn't happen
