### ISSUE TITLE
Question: Chunk Loading and Gendustry/Advanced Generators/Pressure Pipes

### ISSUE THREAD

**Issue by GodNero** [bdew-minecraft/gendustry#98]
Hello,

I have an odd question for you, are there any blocks in your mods that are self loading and/or force load chunks? I seem to be having an odd issue where one of our test servers seems to be loaded and working, in this case industrial apiaries are still producing honey comb when they shouln't be as the area is not chunk/force loaded.

Nero,
RR3 PackDev

**Comment by bdew** [comment]
I don't do any chunk (force) loading in any of my mods.

Note that bees (depending on traits and upgrades) can have pretty big ranges on their effects and spreading flowers/pollination. When any of those are applied at random to an unloaded chunk it will be loaded for a while and during that time something in it could cause other chunks to be loaded - basically creating a loop of chunks loading each other.

This is not something specific to my mods, you can even get the same effect in vanilla with e.g. chained hoppers across chunk boundaries.

**Comment by GodNero** [comment]
hmmm that is a possibility I will need to check to see if i am crossing boundaries then.

**Comment by GodNero** [comment]
Ookay confirmed that my bees are sitting in the corner of two boundaries, thus their territories are more then likely covering four chunks. I will move them and see if this helps with this.
